### ISSUE TITLE
Filename validity checking

### ISSUE THREAD

**Issue by fabiolib** [ratschlab/spladder#10]
Thanks for this very useful tool. Your tool in default mode runs through splice graph augmentation first before opening the bam alignment file. If the path to the bam file is wrong the error only occurs after this step, when the user may not be present at the terminal. Furthermore, the final line in the TraceBack `AttributeError: 'NoneType' object has no attribute 'shape'` isn't very helpful. So perhaps an initial check for the presence of all the files the user has supplied (a la [os.path.isfile](https://docs.python.org/dev/library/os.path.html#os.path.isfile)) and a simple error message before any computation begins would be useful?

**Comment by akahles** [comment]
Thank you very much for the useful feedback. I have added the input file checking to the arg parser in this commit f66bc235d61beef923848e2239526b46815db079. Please re-open, if necessary.
