### ISSUE TITLE
FutureWarning from scipy?

### ISSUE THREAD

**Issue by jfass** [ratschlab/spladder#100]
* spladder version: 2.3.0
* Python version: 3.5
* Operating System: Ubuntu 16

### Description

Event calling step for several human chromosomes, ~32 samples, has been running for almost a week. All chromosomes have generated this warning:

```
/home/ubuntu/spladder/spladder-2.3.0-venv/lib/python3.5/site-packages/scipy/sparse/lil.py:518: FutureWarning: future versions will not create a writeable array from broadcast_array. Set the writable flag explicitly to avoid this warning.
  if not x.flags.writeable:
```

### What I Did

Ran all chr separately (separate directories) up through '--qmode collect', then event calling:

```
cat chrList.txt | while read chr; do
  spladder build -o spladder_out.${chr} -a gencode.v19.annotation.pc.${chr}.gtf \
    -b $allbams --parallel 2 -c 0 --set-mm-tag nM --readlen 150 \
    --merge-strat merge_graphs --no-extract-ase --quantify-graph --qmode collect \
    2>${chr}.qmodeCollect.err 1>${chr}.qmodeCollect.out &
done
```

Not sure if the warnings are related to the week-long runs. Some chromosomes seem to have finished without problems, so this may not be a problem, just a long run time for some complicated chromosomes (17, 21).

**Comment by jfass** [comment]
Update: killed the processes this morning; they've been running for 3 weeks. Andre, could you suggest some time-saving options to investigate first? How would you diagnose what was taking so long for my data?
Thanks,
~Joe

**Comment by akahles** [comment]
Hi Joe,
does the run stall at the event detection stage? The above code shows the `collect` step from the distributed build.
Some way to parallelise is to do the event calling per event type and run all different types in parallel. A second way to reduce complexity (if one of the event types fails), would be to ignore too complex graphs. You can set the limit via `--ase-edge-limit`.

Cheers,

Andre

**Comment by jfass** [comment]
Ah ... right ... I didn't think of parallelizing by event type. I've now gotten most chromosomes to finish on all but ~7 chromosomes, across 372 samples, including each vs remaining (so, 372 separate) 'spladder test' runs ... but see [Issue #97 ](https://github.com/ratschlab/spladder/issues/97) for the errors I'm seeing on the remaining chromosomes ... seems like it could be the same error, but in a different place?
~Joe

**Comment by jfass** [comment]
... and I'll close this issue until I hit long run times again
Thanks Andre
