### ISSUE TITLE
Inconsistent event IDs

### ISSUE THREAD

**Issue by jfass** [ratschlab/spladder#103]
* spladder version: 2.3.0

### Description

This is very minor, but mildly annoying for downstream processing. Events in the "merge_graphs*.confirmed.txt.gz" appear like this:

```
intron_retention_472
```

But in the GFF3 files, they appear like this:

```
intron_retention.472
intron_retention.472_iso1
```

If it'd be easy to fix, to keep the underscores and dots consistent, that'd be great.

**Comment by jfass** [comment]
Minor correction #2: 'spladder build --help' list of the event types includes the misspelled "mtex_exons"

**Comment by akahles** [comment]
Both should be fixed in development now. Will be merged into master soon and become available with the next release. Please re-open if still relevant.
