### ISSUE TITLE
Test mode error (merging strategy)

### ISSUE THREAD

**Issue by play131937** [ratschlab/spladder#105]
* spladder version: 2.3.0
* Python version: 3.6.7 
* Operating System: CentOS Linux release 7.6.1810 (Core)

### Description

What I have done is,
```
spladder build -a ~/genome/Arabidopsis_thaliana/Athaliana_167_TAIR10.gene_exons.gff3 -b S4-2C_L1.bam,S4-2E_L1.bam,S9-2C_L1.bam,S9-2E_L1.bam -o ~/AlternativeSplicing/
```
and this is how the output folder looked like
```
~/AlternativeSplicing/
├── merge_graphs_alt_3prime_C3.confirmed.gff3
├── merge_graphs_alt_3prime_C3.confirmed.pickle
├── merge_graphs_alt_3prime_C3.confirmed.txt.gz
├── merge_graphs_alt_3prime_C3.counts.hdf5
├── merge_graphs_alt_3prime_C3.pickle
├── merge_graphs_alt_5prime_C3.confirmed.gff3
├── merge_graphs_alt_5prime_C3.confirmed.pickle
├── merge_graphs_alt_5prime_C3.confirmed.txt.gz
├── merge_graphs_alt_5prime_C3.counts.hdf5
├── merge_graphs_alt_5prime_C3.pickle
├── merge_graphs_exon_skip_C3.confirmed.gff3
├── merge_graphs_exon_skip_C3.confirmed.pickle
├── merge_graphs_exon_skip_C3.confirmed.txt.gz
├── merge_graphs_exon_skip_C3.counts.hdf5
├── merge_graphs_exon_skip_C3.pickle
├── merge_graphs_intron_retention_C3.confirmed.gff3
├── merge_graphs_intron_retention_C3.confirmed.pickle
├── merge_graphs_intron_retention_C3.confirmed.txt.gz
├── merge_graphs_intron_retention_C3.counts.hdf5
├── merge_graphs_intron_retention_C3.pickle
├── merge_graphs_mult_exon_skip_C3.confirmed.gff3
├── merge_graphs_mult_exon_skip_C3.confirmed.pickle
├── merge_graphs_mult_exon_skip_C3.confirmed.txt.gz
├── merge_graphs_mult_exon_skip_C3.counts.hdf5
├── merge_graphs_mult_exon_skip_C3.pickle
├── merge_graphs_mutex_exons_C3.confirmed.gff3
├── merge_graphs_mutex_exons_C3.confirmed.pickle
├── merge_graphs_mutex_exons_C3.confirmed.txt.gz
├── merge_graphs_mutex_exons_C3.counts.hdf5
├── merge_graphs_mutex_exons_C3.pickle
├── S4-2C_L1.bam 
├── S4-2C_L1.bam.bai
├── S4-2Ea_L1.bam 
├── S4-2Ea_L1.bam.bai
├── S9-2C_L1.bam 
├── S9-2C_L1.bam.bai
├── S9-2Ea_L1.bam 
├── S9-2Ea_L1.bam.bai
├── spladder/
    ├── genes_graph_conf3.merge_graphs.count.hdf5
    ├── genes_graph_conf3.merge_graphs.count.hdf5.quick_edge_idx
    ├── genes_graph_conf3.merge_graphs.count.hdf5.quick_ids_edges
    ├── genes_graph_conf3.merge_graphs.count.hdf5.quick_ids_segs
    ├── genes_graph_conf3.merge_graphs.pickle
    ├── genes_graph_conf3.S0304-2C_L1.pickle
    ├── genes_graph_conf3.S0304-2Ea_L1.pickle
    ├── genes_graph_conf3.S0319-2C_L1.pickle
    └── genes_graph_conf3.S0319-2Ea_L1.pickle
└── tmp/
```

However, when I tried to run `test` mode for differential analysis by the command line below,
```
spladder test -M merge_graphs -a S4-2C_L1.bam,S9-2C_L1.bam -b S4-2Ea_L1.bam,S9-2Ea_L1.bam --labelA Ctrl --labelB mVCs -D --plot-format pdf -o spladder/   
``` 
I got this error,

```
ERROR: Testing mode can only be run on SplAdder outputs generated using the default merging strategy: --merge-strat merge_graphs
```

### What I Did

I have tried to run the `test` mode command under both **~/AlternativeSplicing/** and **~/AlternativeSplicing/spladder/** folder to see whether it was pathway setting problem or not, but I got the same error.

Any suggestion would be helpful.

Thanks, 
Iris

**Comment by akahles** [comment]
Dear Iris, 

thank you for reporting this issue and apologies for the late reply. The error message is a bit misleading. What SplAdder does is to check whether the file `spladder/genes_graph_conf3.merge_graphs.pickle` exists where it expects it to be. I will put it on my ToDo list to make that message more meaningful.

In your calls I see that you call `build` and `test` mode with different output directories (using `-o`). Do they have the same contents? If not, then SplAdder will not be able to find the above mentioned file.

Best,

Andre

**Comment by play131937** [comment]
Hi Andre,

Thanks for reply. I use the same output directory and then it works!!

Best,

Iris

**Comment by mhjiang97** [comment]
> Hi Andre,
> 
> Thanks for reply. I use the same output directory and then it works!!
> 
> Best,
> 
> Iris

Hi Iris,

I am confused about how to figure out if an alternative splicing in the spladder output files is an annotated one in user-provided gtf. Do you have any idea about this question? If I cannot directly know which alternative splicing event is already annotated from the spladder output files, what should I do to solve it?
Thank you very much! I'm looking forward to your reply~

Best,
Minghao

**Comment by play131937** [comment]
Hi Minghao,

Apologies for the late reply. Could you show me the output file or offer more information for your question to help figuring out?

Thanks,

Iris

**Comment by akahles** [comment]
Dear Iris and Minghao,

SplAdder currently does not track for the events whether they are annotated or novel. I will add this feature in the next release. Meanwhile what you can do to create events on the annotation only, you can run the program like so:
```
spladder build  --no-insert-ir --no-insert-es --no-insert-ni --no-quantify-graph -a <anno> -b <bam> -o <out> ...
```
This will create a splicing graph from the annotation without adding any information from RNA-Seq data. (The command line requires a single bam file to be present, but no data will be extracted from it.) These events can then be compared to the ones created using the RNA-Seq data.

Cheers,
Andre

**Comment by play131937** [comment]
Hi Andre,

Thanks for the information. So does the HDF5 files generated from `spladder build` still work?
I have this question because when I was trying to extract read counts data by the command,

```
kallisto h5dump ../spladder/genes_graph_conf3.merge_graphs.gene_exp.hdf5 -o ./
```  
I got the error,

```
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140613050033984:
  #000: H5G.c line 470 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: H5Gint.c line 318 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: H5Gloc.c line 422 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #005: H5Gloc.c line 378 in H5G__loc_find_cb(): object 'aux' doesn't exist
    major: Symbol table
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140613050033984:
  #000: H5D.c line 282 in H5Dopen2(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 246 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140613050033984:
  #000: H5D.c line 482 in H5Dget_create_plist(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140613050033984:
  #000: H5Pocpl.c line 888 in H5Pget_filter2(): can't find object for ID
    major: Object atom
    minor: Unable to find atom information (already closed?)
  #001: H5Pint.c line 3822 in H5P_object_verify(): property list is not a member of the class
    major: Property lists
    minor: Unable to register new atom
  #002: H5Pint.c line 3772 in H5P_isa_class(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140613050033984:
  #000: H5D.c line 445 in H5Dget_type(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140613050033984:
  #000: H5D.c line 372 in H5Dget_space(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140613050033984:
  #000: H5S.c line 1013 in H5Sget_simple_extent_dims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140613050033984:
  #000: H5T.c line 2131 in H5Tget_size(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 140613050033984:
  #000: H5Dio.c line 177 in H5Dread(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```  

I had no experience with HDF5 before, so I am not sure whether this is due to my HDF5 files or HDF5 library or other reasons that I did not notice. Do you have any ideas about how to fix it? Or if this is not about spladder, I would try HDF5 forum or google.

Thanks,
Iris

**Comment by akahles** [comment]
Hi Iris,

I am not quite sure what the goal of the above command is, but HDF5 is just a container file format that contains the count data. You can access it from many languages using the appropriate hdf5 module. For instance, for Python I would recommend h5py. 

To check the contents of the file from the command line, you can use:/
```
h5ls -r spladder/genes_graph_conf3.merge_graphs.gene_exp.hdf5
```

Cheers,

Andre

**Comment by OnkarMulay** [comment]
> Dear Iris,
> 
> thank you for reporting this issue and apologies for the late reply. The error message is a bit misleading. What SplAdder does is to check whether the file `spladder/genes_graph_conf3.merge_graphs.pickle` exists where it expects it to be. I will put it on my ToDo list to make that message more meaningful.
> 
> In your calls I see that you call `build` and `test` mode with different output directories (using `-o`). Do they have the same contents? If not, then SplAdder will not be able to find the above mentioned file.
> 
> Best,
> 
> Andre

Hi,
Can you tell me when this file is not created? Because after build I check error message it says genes_graph_conf3.merge_graphs.pickle not found, it means during build only this didn't get created

**Comment by akahles** [comment]
I am closing this, as the original issue has been addressed. Also, the labelling of whether an event is annotated has been added with the latest release. Please open a new issue, if anything still pops up with the latest release.

Best,
Andre
