### ISSUE TITLE
a question about the running time of spladder

### ISSUE THREAD

**Issue by mhjiang97** [ratschlab/spladder#108]
* spladder version: 2.4.2
* Python version: 3.7.4
* Operating System: Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018

### Description
when I used spladder to create an individual splicing graph for one input sample on the supercomputer, it took me nearly two and a half hours. I'd like to know if this cost is normal? Thank you very much!

### What I Did
spladder build -o /my/output/dir/spladder_out -a /path/to/gtf/gencode.v31.annotation.gtf -b /path/to/bam/PANLGK.sortedByCoord.bam --merge-strat single -n 50 -c 2 --set-mm-tag nM --ase-edge-limit 300 --parallel 1000 --no-extract-ase

**Comment by jjyotikataria** [comment]
Hi @mhjiang97 
Were you able to reduce the running time of the build command?
Its really not working out for me. It takes more than 8-9 hours for 2 gb bam files (4 files).

**Comment by mhjiang97** [comment]
> Hi @mhjiang97
> Were you able to reduce the running time of the build command?
> Its really not working out for me. It takes more than 8-9 hours for 2 gb bam files (4 files).

Hi @jjyotikataria 
i'm afraid that the software doesn't run as quickly as expected. my only advice is run spladder on a powerful computer.

**Comment by akahles** [comment]
Running time depends on the complexity of the input. Sequencing depth, number of splice junctions, etc influence the complexity of the graph and hence running time.

However, 8h for 2gb is unexpectedly long. Is the 8h for all 4 files together? Are you running SplAdder in `merge_graphs` mode? If this is the case, then every sample is run sequentially and a running time of 2h per file can easily happen. 

One option to speed this up is to run the individual samples in parallel. Some instructions on how to do this can be found here:
https://spladder.readthedocs.io/en/latest/spladder_cohort.html
(This also includes the hint to use `--sparse-bam` to speed up quantification.)

Lastly, there is a number of improvements on our todo list, one of which is to Cythonize some parts of the code so it runs faster.

Hope this helps.

Cheers,
Andre

**Comment by mhjiang97** [comment]
Thank you very much for your time!

**Comment by jjyotikataria** [comment]
Hi @akahles 
Thankyou. Ill go through this. Yes, Im running in merge graphs mode.  Yes more than 8 hours for 4 (2-2.5 Gb bam files). Then it gave me a memory issue error. It was still running but nothing happening, I had to kill it.

**Comment by akahles** [comment]
I am closing this for now. Please re-open, if still relevant.
