### ISSUE TITLE
sample naming error in spladder output

### ISSUE THREAD

**Issue by PhilippMarkolin** [ratschlab/spladder#110]
* spladder version: 2.4.2
* Python version:
* Operating System: mac

### Description
Running spladder build --merge strat single on melanoma batch 4. Found a sample name error in the output pickle file. Problem in one sample named "MAHO**BAM**.all.bam", which gets shorted to "MAH.all.bam"

### What I Did
`cat /cluster/work/grlab/projects/tmp_philipp/immunopepper/TP_melanoma_batch4/hg38_run/samples.txt`
/cluster/work/grlab/projects/tmp_tinu/debug_ratschlab_snakemake/TP_runs/hg38_runs/melanoma_batch4_results/alignments/MADEGOD.all.bam
/cluster/work/grlab/projects/tmp_tinu/debug_ratschlab_snakemake/TP_runs/hg38_runs/melanoma_batch4_results/alignments/MAHOBAM.all.bam
/cluster/work/grlab/projects/tmp_tinu/debug_ratschlab_snakemake/TP_runs/hg38_runs/melanoma_batch4_results/alignments/MEKAKYD.all.bam
/cluster/work/grlab/projects/tmp_tinu/debug_ratschlab_snakemake/TP_runs/hg38_runs/melanoma_batch4_results/alignments/MEZYWEG.all.bam

I ran this script:
```
#!/usr/bin/bash
#create single graph per sample

source activate spladder

outdir=/cluster/work/grlab/projects/tmp_philipp/immunopepper/TP_melanoma/hg38_run
genome=/cluster/work/grlab/projects/tumor_profiler/annotation/gencode.v32.annotation.gtf

for sample in $(cat /cluster/work/grlab/projects/tmp_philipp/immunopepper/TP_melanoma_batch4/hg38_run/samples.txt) 

do 

	bsub -M 10000 -R "rusage[mem=10000]" -W 20:00 -J philipp "spladder build -a $genome -b $sample -o $outdir --merge-strat single --confidence 2 --no-extract-ase"
done
```

The resulting spladder folder looks like this:
`(base) [maphilip@lm-login-01 spladder]$ ls -lh`
total 5.0G
-rw-r--r-- 1 maphilip INFK-Raetsch-Collab 289M Feb  4 22:10 genes_graph_conf2.MADEGOD.all.pickle
-rw-r--r-- 1 maphilip INFK-Raetsch-Collab 338M Feb  4 23:53 genes_graph_conf2.MAH.all.pickle
-rw-r--r-- 1 maphilip INFK-Raetsch-Collab 328M Feb  4 22:15 genes_graph_conf2.MEKAKYD.all.pickle
-rw-r--r-- 1 maphilip INFK-Raetsch-Collab 282M Feb  4 21:49 genes_graph_conf2.MEZYWEG.all.pickle

**Comment by akahles** [comment]
This has been fixed in the latest release.
