### ISSUE TITLE
Running spladder viz mode

### ISSUE THREAD

**Issue by jjyotikataria** [ratschlab/spladder#112]
* spladder version:
* Python version:3.6.4
* Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.2:GA:server
            Kernel: Linux 3.10.0-327.el7.x86_64

### Description

I ran the build command as follows, now I need to see viz mode results.

### What I Did
/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/bin/spladder build -o . -b /home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/SH9.Aligned.sortedByCoord.out.bam,/home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/SH7.Aligned.sortedByCoord.out.bam -a /home/jyoti.k/TESTING/SPLADDER/SPLADDER_RESULTS/NEW_Homo_sapiens.GRCh37.75.gtf --parallel 5 -c 2

I got these files per event, so I have 5*6 = 30 files
merge_graphs_alt_3prime_C2.confirmed.gff3       
merge_graphs_alt_3prime_C2.confirmed.pickle     
merge_graphs_alt_3prime_C2.confirmed.txt.gz     
merge_graphs_alt_3prime_C2.counts.hdf5          
merge_graphs_alt_3prime_C2.pickle  

I ran viz mode

/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/bin/spladder viz -o .

I got no results in plots folder.
```

**Comment by akahles** [comment]
Dear @jjyotikataria,

In your visualisation command you do not specific what to visualise. You can find more information on how to use `viz` mode in the documentation:
https://spladder.readthedocs.io/en/latest/spladder_modes.html#the-viz-mode

I hope that helps.

Cheers,

Andre
