### ISSUE TITLE
Example data

### ISSUE THREAD

**Issue by jjyotikataria** [ratschlab/spladder#113]
* spladder version:
* Python version:3.6.4
* Operating System:   Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)

### Description

I ran the build mode for the example data but looks like there are two types of samples pos and neg
And there are two annotation gts present in there. So, do I need to run the build twice?

### What I Did
I ran it for pos first taking all pos bam files and pos gtf annotation file

/home/jyoti.k/TESTING/SPLADDER/Python-3.6.4/bin/spladder build -o . -b spladder-master/tests/testcase_basic/data/align/pos_1.bam,spladder-master/tests/testcase_basic/data/align/pos_2.bam,spladder-master/tests/testcase_basic/data/align/pos_3.bam,spladder-master/tests/testcase_basic/data/align/pos_4.bam,spladder-master/tests/testcase_basic/data/align/pos_5.bam -a spladder-master/tests/testcase_basic/data/annotation_pos.gtf

```

**Comment by akahles** [comment]
You can run SplAdder on all its testdata by typing `make test` from the installation directory. 

If you are interested how the test set was generated, you can have a look in `scripts/generate_test_results.sh` and `scripts/generate_test_results_events.sh`.
