### ISSUE TITLE
Documentation on column headers of txt output

### ISSUE THREAD

**Issue by junghoon-shin** [ratschlab/spladder#116]
* spladder version: 2.4.2
* Python version: 3.7.6
* Operating System: Ubuntu 18.04

### Description

I'm trying to understand what exactly each column header of the `spladder build` txt output means. Some of them are described in the File format section of the documentation (https://spladder.readthedocs.io/en/latest/file_formats.html), but some not. For example, there are columns named "<file_id>:intron_pre_conf", "<file_id>:intron_inner_conf", "<file_id>:intron_aft_conf", "<file_id>:intron_skip_conf" in the txt output of multiple exon skip events, and I couldn't find description on the meaning of these columns anywhere in the documentation. Here is what I guess.

intron_pre_conf = exon_pre_exon_conf
intron_inner_conf = sum_inner_exon_conf
intron_aft_conf = exon_exon_aft_conf
intron_skip_conf = exon_pre_exon_aft_conf

But I couldn't find any formal documentation to confirm this is correct.

**Comment by akahles** [comment]
This has been adapted with the latest release and was now also added to the docs. Please re-open if still an issue.
