### ISSUE TITLE
How spladder decides which alternative splicing event to be used as a numerator in psi calculation

### ISSUE THREAD

**Issue by junghoon-shin** [ratschlab/spladder#117]
* spladder version: 2.4.2
* Python version: 3.7.6
* Operating System: Ubuntu 18.04

### Description

According to the Supplementary material of the original publication (https://doi.org/10.1093/bioinformatics/btw076), a mini-gene always consists of two alternative and mutually exclusive splicing events. Between these two events, selecting the one to be used as a numerator in psi calculation is straightforward for the exon skip, intron retention, and multiple exon skip categories. But is there any rule in selecting which event to be used as a numerator for psi calculation in case of alternative 3', alternative 5', and mutually exclusive exon events (for example, always choosing the one with a more promoter-proximal alternative splice site)? I ask this because there is no mention about this in the publication nor in the documentation and I couldn't figure out one from the results.

**Comment by szkabel** [comment]
We figured out the following from the code and the sample dataset in the repo:

If you check the merge_graphs_[event_type]_C[X]_confirmed.gff3 files for each event you always have the iso1 and iso2 "mini-genes" defined. According to these definitions PSI quantifies iso1/(iso1+iso2) **only** for Mutex exons. In all other cases (Alt3', Alt5', Exon skip, Multiple exon skip, Intron retention) PSI is the ratio of iso2/(iso1+iso2).

So, PSI>0 in Mutex means evidence for the presence of iso1, but in all other cases PSI>0 is evidence for the presence of iso2.

This still doesn't answer how the actual events (merge_graphs) are defined from the splicing graph but at least gives you a reference on which branch is quantified.

**Comment by akahles** [comment]
This inconsistency relates to issue #132 . This has been fixed with the latest release. 
Please re-open, in case there is still something wrong.
