### ISSUE TITLE
Question about validate-sg-count option

### ISSUE THREAD

**Issue by ProfessionalFarmer** [ratschlab/spladder#122]
* spladder version: 2.4.2
* Python version: 3.8.3
* Operating System: Ubuntu

### Description

In the spladder document build section, '--validate-sg-count' was introduced, but when I added this option in my analysis, an error occurred with 'unrecognized arguments' information. 

Inside the spladder.py file, I didn't see this option inside build section.

May I know whether this option is still available? 

Thanks

Jason

**Comment by AlexWeinreb** [comment]
It seems this option is not available from the command line, but is defined in the `settings.py` file. I tried changing this line (93):

    options.sg_min_edge_count = 10

and it seems to work as expected.

However I don't know if the developer removed it from the CLI interface on purpose, and would be interested to know if its use is discouraged.

**Comment by akahles** [comment]
Thank you for reporting this. It is indeed a bug in the CLI and will be fixed in the upcoming release.
