### ISSUE TITLE
No txt/gff output files are generated after spladder builld run

### ISSUE THREAD

**Issue by junghoon-shin** [ratschlab/spladder#123]
* spladder version: 2.4.2
* Python version: 3.8.3
* Operating System: Ubuntu 18.04

### Description

I ran the exact same codes shown on the documentation page for large cohorts (https://spladder.readthedocs.io/en/latest/spladder_cohort.html) step by step (from generating a splice graph for each sample all the way through event calling) using my own 100 RNA-Seq bam files as input. But in the output directory, there are no txt or gff3 files generated (there are only pickle and hdf5 files). Do I need to explicitly specify the output options (e.g., --output-txt-conf, --output-gff3-conf) to get those files? 

### What I Did

```
while read bam
do
        spladder build \
                --bams "$bam" \
                --annotation "<GENCODE_GTF>" \
                --outdir "<OUTPUT_DIR>" \
                --merge-strat single \
                --no-extract-ase &
done < input_bam_list.txt
wait

spladder build \
        --bams input_bam_list.txt \
        --annotation "<GENCODE_GTF>" \
        --outdir "<OUTPUT_DIR>" \
        --merge-strat merge_graphs \
        --no-extract-ase

while read bam
do
        spladder build \
                --bams "$bam" \
                --annotation "<GENCODE_GTF>" \
                --outdir "<OUTPUT_DIR>" \
                --merge-strat merge_graphs \
                --no-extract-ase \
                --quantify-graph \
                --qmode single &
done < input_bam_list.txt
wait

spladder build \
        --bams input_bam_list.txt \
        --annotation "<GENCODE_GTF>" \
        --outdir "<OUTPUT_DIR>" \
        --merge-strat merge_graphs \
        --no-extract-ase \
        --quantify-graph \
        --qmode collect

spladder build \
        --bams input_bam_list.txt \
        --annotation "<GENCODE_GTF>" \
        --outdir "<OUTPUT_DIR>"
```

**Comment by akahles** [comment]
SplAdder will only report outputs for events it considers "valid" based on the provided read data. If an event does not have read support in any of the provided samples, it will not be reported. The stringency of this reporting can be influenced with the confidence levels. It is still on my todo list to allow for a more fine-grained configuration providing a config file.

For now, I would suggest to reduce the confidence level and see whether this helps.

**Comment by akahles** [comment]
Please reopen if still relevant.
