### ISSUE TITLE
Which way should I run spladder?

### ISSUE THREAD

**Issue by mhjiang97** [ratschlab/spladder#124]
* spladder version: latest
* Python version: 3.7.4
* Operating System: Linux version 3.10.0-862.el7.x86_64

### Description
I downloaded 2000 leukemia bams consisted of multiple subtypes, and what I am trying to do is to explore how many alternative splicing events in every subtype.

Thus, should I run all bam files in the same output directory, or run separately according to subtypes and analysis the output in different directories?

thank you very much!

**Comment by akahles** [comment]
We usually build a joint graph on all input samples and jointly call events. For 2000 input samples, this can be some effort. I would recommend having a look at this section in the documentation:
https://spladder.readthedocs.io/en/latest/spladder_cohort.html

So I would suggest to run everything into the same output directory, but parallelise over input samples as far as possible.

**Comment by mhjiang97** [comment]
Thank you for explanation.
As far as I understand, the final output file, for example, merge_graphs_intron_retention_C3.confirmed.txt.gz, contains all events from the whole cohort.
If I want to seek out events belonging to a specific subgroup from all samples, is extracting the subgroup and excluding events having nan psi value among the subgroup a proper way?

**Comment by akahles** [comment]
Sorry for the late reply. Your suggestion makes sense to me as long as you don't take the NaN as evidence for the absence of a splicing event in a given sample. The only way this can be interpreted is that there is no sufficient evidence in the input data for SplAdder to call an event in this sample. However, also this does not proof tissue specificity of an event, it can be seen as an indication for it.

**Comment by mhjiang97** [comment]
> Sorry for the late reply. Your suggestion makes sense to me as long as you don't take the NaN as evidence for the absence of a splicing event in a given sample. The only way this can be interpreted is that there is no sufficient evidence in the input data for SplAdder to call an event in this sample. However, also this does not proof tissue specificity of an event, it can be seen as an indication for it.

I got it. Many thanks!
