### ISSUE TITLE
where is the other events all over the genome ?

### ISSUE THREAD

**Issue by cfyin** [ratschlab/spladder#125]
* spladder version:2.4.2
* Python version:3.7
* Operating System:centos 6.4

### Description
Spladder is a nice tool  for splicing analysis on RNAseq data.
I got only about 3000 event lines of my samples, but the number of predicted introns is >10k all over the genome.
My question is why cannot  I see the other events all over the genome ?
In my opinion, the other events were ignored because there was no difference between all samples.
The parament to control this is '-c' ?  I set it 3.
Is that ture ?

**Comment by akahles** [comment]
Thank you for using SplAdder. The SplAdder heuristic strongly depends on the amount and quality of input data. How many reads of what length have you in your input? What size is the genome you are working on? Lowering the confidence level from the default 3 to something like 2 or 1 will increase the amount of spliced reads considered, but will inevitably also increase the amount of noise and possibly artifactual edges in the splicing graph.

**Comment by akahles** [comment]
Please re-open if still relevant.
