### ISSUE TITLE
How is the PSI value generated in each splice type

### ISSUE THREAD

**Issue by yjzhang2013** [ratschlab/spladder#127]
* spladder version: latest
* Python version: 3.6
* Operating System: linux-ubuntu
Hi, 
    With the produced read counts, for A3/A5 and RI, it is eazy to speculate that PSI=intron_conf2/(intron_conf1+intron_conf2）, and intron_cov/(intron_cov+intron_conf) seperately. However, for ES and other splice types, could you provide details about the definition of isoform-specific read counts and how is the PSI value generated? Thank you!
Sincerely,
Yangjun

**Comment by yjzhang2013** [comment]
In the 'spladder/spladder/helpers.py' file, I have found the answer.
However, I'm still confused about the reason using min(counts[:, 4], counts[:, 5]) rather than average(counts[:, 4], counts[:, 5]) for exon skip type.

########
def compute_psi(counts, event_type, options):
    ### collect count data based on event type
    if event_type == 'exon_skip':
        #a = counts[:, 4] + counts[:, 5]
        #b = 2 * counts[:, 6]
        a = sp.c_[counts[:, 4], counts[:, 5]].min(axis=1)
        b = counts[:, 6]
    elif event_type == 'intron_retention':
        a = counts[:, 1] # intron cov
        b = counts[:, 4] # intron conf
    elif event_type in ['alt_3prime', 'alt_5prime']:
        a = counts[:, 4] # intron2 conf
        b = counts[:, 3] # intron1 conf
    elif event_type == 'mutex_exons':
        a = counts[:, 5] + counts[:, 7] # exon_pre_exon1_conf + exon1_exon_aft_conf
        b = counts[:, 6] + counts[:, 8] # exon_pre_exon2_conf + exon2_exon_aft_conf
    elif event_type == 'mult_exon_skip':
        a = counts[:, 4] + counts[:, 5] + counts[:, 7] # exon_pre_exon_conf + exon_exon_aft_conf + sum_inner_exon_conf
        b = (counts[:, 8] + 1) * counts[:, 6] # (num_inner_exon + 1) * exon_pre_exon_aft_conf
    else:
        raise Exception('Unknown event type: %s' % event_type)
########

**Comment by akahles** [comment]
Thank you for looking into this. Using the min over the two junction counts flanking the inner exon is the more conservative approach for quantification. For instance, if you look at two flanking sets of introns (i1, i2) = (50, 50) and (j1, j2) = (100, 0), then the average of the two is in both cases 50, although the evidence for the definition of the inner exon is much stronger for (i1, i2), as both splice sites are supported by 50 spliced alignments, than in (j1, j2), where there is no read support for the exon end. Using the min will better reflect that uncertainty.

**Comment by yjzhang2013** [comment]
Thank you for replying. I agree that this method can be used to balance that uncetainty in exon skip. It seems that this uncetainty also existed in mutex exons, then why use i1+i2 (exon_pre-exon_1 and exon_1-exon_aft) to replace min(i1, i2) in that case? Does i1+i2 bring more confirmed mutex exons events?
Thanks again.
Yangjun

**Comment by yjzhang2013** [comment]
> 
> 
> Thank you for looking into this. Using the min over the two junction counts flanking the inner exon is the more conservative approach for quantification. For instance, if you look at two flanking sets of introns (i1, i2) = (50, 50) and (j1, j2) = (100, 0), then the average of the two is in both cases 50, although the evidence for the definition of the inner exon is much stronger for (i1, i2), as both splice sites are supported by 50 spliced alignments, than in (j1, j2), where there is no read support for the exon end. Using the min will better reflect that uncertainty.

Thank you for replying. I agree that this method can be used to balance that uncetainty in exon skip. It seems that this uncetainty also existed in mutex exons, then why use i1+i2 (exon_pre-exon_1 and exon_1-exon_aft) to replace min(i1, i2) in that case? Does i1+i2 bring more confirmed mutex exons events?
Thanks again.
Yangjun

**Comment by akahles** [comment]
I see your point here. i1+i2 brings more mutex exon events, as the condition is weaker and confirmation of a single flanking exon is sufficient. However, I would argue the same way as I did for the exon skipping and prefer the min. I will make this consistent in the new release and add an option for the "classical" PSI behavior.
