### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by Estherrr1997** [ratschlab/spladder#128]
* spladder version: 2.4.2(?) -- I just did the pip install spladder
* Python version: 3.9
* Operating System: Linux

### Description

I ran the following commands:

pip install spladder
##### clone repository:
git clone https://github.com/ratschlab/spladder
##### go to the spladder directory:
cd spladder
sudo make install (I get an error when I don't use the "sudo")

pip install pytest
make test

< ERROR >

I wanted to test spladder using the "make test command" although I get a really long error (see attachment).
[error_make_test.txt](https://github.com/ratschlab/spladder/files/5926607/error_make_test.txt)

I hope you can help me.

Kind regards,

**Comment by akahles** [comment]
Dear @Estherrr1997 , 

when installing SplAdder via pip, there is no need to run further installation. The cloning of the git repository is not necessary.

However, if you would like to install from source, you can do the following:

```
### clone project
git clone https://github.com/ratschlab/spladder.git
cd spladder 

### install dependencies
pip install -r requirements.txt
pip install -r requirements_dev.txt

### install
make install

### test
make test
```
Again, if you installed SplAdder via pip, then this is not necessary and you can directly use it.

Best,

Andre

**Comment by Estherrr1997** [comment]
@akahles 

Thanks for your quick respond.when I install SplAdder from source I still get an error.
After the "make test" command I get the following error:

Makefile:62: recipe for target 'test' failed
make: *** [test] Error 2

Is there a way to test if the "pip install spladder" worked?
Like, is there any test data available?

Kind regards,
Esther

**Comment by Estherrr1997** [comment]
@akahles 

I think I fixed the problem, Im able to run spladder now using the test files.
I have downloaded the test data from https://bmi.inf.ethz.ch/supplements/spladder
when I run spladder I get an error:

esther@esther-ThinkPad-S3-Yoga-14:~/Documents/SplAdder/spladder$ spladder build -o output_directory -b test.bam -a test.gff3
Traceback (most recent call last):
  File "/home/esther/.local/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/home/esther/.local/lib/python3.9/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/home/esther/.local/lib/python3.9/site-packages/spladder/spladder_build.py", line 74, in spladder
    (genes, options) = init.init_genes_gff3(options)
  File "/home/esther/.local/lib/python3.9/site-packages/spladder/init.py", line 202, in init_genes_gff3
    tags = get_tags_gff3(sl[8])
IndexError: list index out of range

**Comment by Estherrr1997** [comment]
@akahles 

I found the test data and ran the build command, although I get this error:

**esther@esther-ThinkPad-S3-Yoga-14:~/Documents/SplAdder/spladder$ spladder build -o output_directory -b test.bam -a test.gff3
Traceback (most recent call last):
  File "/home/esther/.local/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/home/esther/.local/lib/python3.9/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/home/esther/.local/lib/python3.9/site-packages/spladder/spladder_build.py", line 74, in spladder
    (genes, options) = init.init_genes_gff3(options)
  File "/home/esther/.local/lib/python3.9/site-packages/spladder/init.py", line 202, in init_genes_gff3
    tags = get_tags_gff3(sl[8])
IndexError: list index out of range
**

Do you know what is going wrong?

Kind regards,
Esther

**Comment by akahles** [comment]
What are the contents of `test.bam` and `test.gff3`?

Best,
Andre

**Comment by Estherrr1997** [comment]
I have downloaded the files from the Example Data available on https://public.bmi.inf.ethz.ch/user/akahles/data/spladder/examples_small/

I used these for the bam files:
NMD_DBL1.tiny.bam
NMD_DBL1.tiny.bam.bai

And I have downloaded the gff3 file from:
https://public.bmi.inf.ethz.ch/user/akahles/data/spladder/TAIR10_GFF3_genes.tiny.gff

**Comment by Estherrr1997** [comment]
Does the error come from the test files?
Or is the error caused by something else?

kind regards,
Esther

**Comment by akahles** [comment]
Sorry for the late reply. I have tested with the data you indicated and the program finishes without issues in my test. Here is what I did. I downloaded all data into a directory `testdata` and ran the following command:
```
spladder build -a testdata/TAIR10_GFF3_genes.tiny.gff -o spladder_out -b testdata/NMD_DBL1.tiny.bam,testdata/NMD_DBL2.tiny.bam,testdata/NMD_WT1.tiny.bam,testdata/NMD_WT2.tiny.bam -v
```
I am closing this for now. Please re-open if the issue still persists.
