### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by anshulmodh** [ratschlab/spladder#130]
* spladder version: 2.4.2
* Python version: 3.6.9
* Operating System: Ubuntu 18.04.5 LTS

### Description

I installed spladder using pip and ran using the default parameters. The script ran into a runtime error on the below assertion.

### What I Did

Command: 
`spladder build -o spladder_1sample -b alignment_files.txt -a annotation.gtf`

Output:

> Remove 0-length intron events
> 
> Make alt_3prime events unique by strain
> Traceback (most recent call last):
>   File "/stor/home/amm9522/.local/bin/spladder", line 11, in <module>
>     sys.exit(main())
>   File "/stor/home/amm9522/.local/lib/python3.6/site-packages/spladder/spladder.py", line 190, in main
>     options.func(options)
>   File "/stor/home/amm9522/.local/lib/python3.6/site-packages/spladder/spladder_build.py", line 252, in spladder
>     collect_events(options)
>   File "/stor/home/amm9522/.local/lib/python3.6/site-packages/spladder/alt_splice/collect.py", line 393, in collect_events
>     events_all = post_process_event_struct(sp.array(alt_end_3prime_pos), options)
>   File "/stor/home/amm9522/.local/lib/python3.6/site-packages/spladder/alt_splice/events.py", line 59, in post_process_event_struct
>     events = make_unique_by_strain(events)
>   File "/stor/home/amm9522/.local/lib/python3.6/site-packages/spladder/alt_splice/events.py", line 96, in make_unique_by_strain
>     assert(event_list[i - 1].gene_name != event_list[i].gene_name)
> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>

**Comment by akahles** [comment]
Dear @anshulmodh, 

Thank you very much for reporting. Would you be able to share your `annotation.gtf` with me?

Thanks,

Andre

**Comment by anshulmodh** [comment]
[Here](https://drive.google.com/file/d/1W4UzZThpGvGKNds08C20DnblISB8AZPq/view?usp=sharing) is a shared link to the annotation.gtf

**Comment by akahles** [comment]
Thank you very much for sharing the file. I was able to re-produce the issue and have fixed it now in the development branch. This fix will become available with the upcoming release.

Thanks,
Andre

**Comment by daniel-spies** [comment]
Dear spladder team,

thanks for the great tool which I already sucessfully used with one dataset but fail to run on a second one (both with custom annotation files). 

the intron_retention and exon_skip parts are succesful though when creating the multi_exon_skip events I fail with an AssertionError.

I also tried with the developmental branch version, though with the same result.  The annotation file used is attached, it does not contain the gene level information (also warning in spladder) though for another custom annotation it worked perfectly fine, any pointers?

thanks in advance
Daniel

[custom_annot.gtf.gz](https://github.com/ratschlab/spladder/files/6473086/custom_annot.gtf.gz)

**Comment by akahles** [comment]
Dear @daniel-spies ,

Thank you for reaching out. I have run SplAdder on your annotation using the latest commit on the development branch (67d91229be570ac824cac46d404708499978233e) and the program ran through without errors. I had to run it without the alignment files, as I did not have access to them. Could you please let me know whether this also fails for you using the same commit? If yes, could you please send me the error message?

Thanks,

Andre

**Comment by daniel-spies** [comment]
Dear Andre,

sorry should have attached the error before ...

yeah 67d9122 is the commit also tried, the splice graph creation also ran through, then during the event detection spladder fails with the following error: 

`confidence 3 / sample 0
Loading gene structure from /mnt/volume1/data/sendoel/RNA-seq/spladder/ataman_nyc_ONT_filt_annot_EpSC/spladder/genes_graph_conf3.merge_graphs.pickle ...
... done.
/mnt/volume1/data/sendoel/RNA-seq/spladder/ataman_nyc_ONT_filt_annot_EpSC/merge_graphs_intron_retention_C3.pickle already exists
/mnt/volume1/data/sendoel/RNA-seq/spladder/ataman_nyc_ONT_filt_annot_EpSC/merge_graphs_exon_skip_C3.pickle already exists

WARNING: not processing gene 39711 (STRG_.80458); has 875 edges; current limit is 500; adjust edge_limit to include.



WARNING: not processing gene 39711 (STRG_.80458); has 875 edges; current limit is 500; adjust edge_limit to include.
/mnt/volume1/data/sendoel/RNA-seq/spladder/ataman_nyc_ONT_filt_annot_EpSC/merge_graphs_intron_retention_C3.pickle already exists
/mnt/volume1/data/sendoel/RNA-seq/spladder/ataman_nyc_ONT_filt_annot_EpSC/merge_graphs_exon_skip_C3.pickle already exists

Remove 0-length intron events

Make mult_exon_skip events unique by strain
. . . events dropped: 0

Make mult_exon_skip events unique by event
Traceback (most recent call last):
  File "/opt/miniconda3/bin/spladder", line 33, in <module>
    sys.exit(load_entry_point('spladder==2.4.3', 'console_scripts', 'spladder')())
  File "/opt/miniconda3/lib/python3.8/site-packages/spladder-2.4.3-py3.8.egg/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/opt/miniconda3/lib/python3.8/site-packages/spladder-2.4.3-py3.8.egg/spladder/spladder_build.py", line 252, in spladder
    collect_events(options)
  File "/opt/miniconda3/lib/python3.8/site-packages/spladder-2.4.3-py3.8.egg/spladder/alt_splice/collect.py", line 356, in collect_events
    events_all = post_process_event_struct(np.array(mult_exon_skip_pos), options)
  File "/opt/miniconda3/lib/python3.8/site-packages/spladder-2.4.3-py3.8.egg/spladder/alt_splice/events.py", line 66, in post_process_event_struct
    events = make_unique_by_event(events)
  File "/opt/miniconda3/lib/python3.8/site-packages/spladder-2.4.3-py3.8.egg/spladder/alt_splice/events.py", line 141, in make_unique_by_event
    assert(event_list[last_kept].strand == event_list[i].strand)
AssertionError
`

many thanks for the help
Daniel

**Comment by akahles** [comment]
Dear Daniel,

Thanks a lot for posting the error. It looks like that you are still using the release version 2.4.3 for your test. If you want to try quickly from the development branch, you can use the following steps:
```
git clone https://github.com/ratschlab/spladder.git spladder_dev
cd spladder_dev
git checkout development
python -m spladder.spladder build <any_other_spladder_parameters_you_used>
```
Best,
Andre

**Comment by daniel-spies** [comment]
Hi Andre,

yeah, forgot the git checkout command, now the make install created the correct version

thanks for the great, fast and patient support

best
Daniel
