### ISSUE TITLE
Is it possible to get splicing event coordinates on differential test output?

### ISSUE THREAD

**Issue by padilr1** [ratschlab/spladder#131]
* spladder version: 2.4.3
* Python version: 3.7
* Operating System: HPC

### Description

For the differential test results, only a given gene is associated with a p-value. Is there some sort of option one can use so that the differential testing phase spits out the coordinates (i.e. the chromosome, start and end coordinates) associated with a significant splicing event as well?

### What I Did

```
spladder test --conditionA WT1.bam,WT2.bam,WT3.bam \
        --conditionB Het4.bam,Het5.bam,Het6.bam \
        -o ${output} \
        --labelA WT \
        --labelB HET \
        --event-types exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip
```

**Comment by padilr1** [comment]
@akahles Thank you too! I have another question: what are the mean even counts calculated from the differential test output? Is it based on the number of exon skipping junctions similar to rMAT?

**Comment by akahles** [comment]
Dear @padilr1 ,

The coordinates have been added to the testing output with the latest release. Also, the documentation has been extended with an explanation regarding the [testing output](https://spladder.readthedocs.io/en/latest/file_formats.html#files-in-txt-format).

I am closing this for now. Please re-open id the issue persists/reappears.

Best,

Andre
