### ISSUE TITLE
Question about zero event detection

### ISSUE THREAD

**Issue by raerose01** [ratschlab/spladder#134]
* spladder version: v2.4.3
* Python version: 3.8.5
* Operating System: Linux

### Description

Hi, I have run Spladder on two test cases -- the first was a simple dataset where I knew there were three intron retention events, and the second was the HCC1395 cell line. Spladder ran perfectly on the first dataset and identified all three RI events. However, it seems to output no events at all for the HCC1395 cell line (which is at odds with other analyses I've seen published on this cell line). I also get the following error with the HCC1395 cell line run.

```
/usr/local/lib/python3.8/dist-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.8/dist-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

I was wondering if this could be an issue with my RNAseq data, or the way I am running Spladder? Though it worked just fine the first test case I ran. Do you know of any common reasons why no events would be detected?

### What I Did

```
spladder build \
                -b analysis/bam/TC5-HCC1395-BL_100_cegat.STAR.genome.sorted.bam \
                -o analysis/spladder/TC5-HCC1395-BL_100_cegat \
                -a reference/ucsc/hg19.refGene.gtf \
                -v \
                -c 2 \
                --event-types intron_retention,alt_3prime,alt_5prime
```

**Comment by raerose01** [comment]
Never mind, I think I figured this out.

**Comment by kate-stankiewicz** [comment]
Hi @raerose01 , I have a similar issue. What was it that you figured out to solve this?

**Comment by raerose01** [comment]
> Hi @raerose01 , I have a similar issue. What was it that you figured out to solve this?

Hi @kate-stankiewicz, I _think_ it was a reference mismatch for me -- the sample had "chr" prefix, and the reference did not.

**Comment by kate-stankiewicz** [comment]
> > Hi @raerose01 , I have a similar issue. What was it that you figured out to solve this?
> 
> Hi @kate-stankiewicz, I _think_ it was a reference mismatch for me -- the sample had "chr" prefix, and the reference did not.

Thanks for the really speedy reply--it's helpful as I can check for that now. What is strange for me is that this warning message only occurs for one of my samples and not any of the others. 

Thanks for tip on the ref being a potential cause!
