### ISSUE TITLE
Identify novel events with respect to annotation

### ISSUE THREAD

**Issue by pablommesas** [ratschlab/spladder#138]
* spladder version: v2.4.4
* Python version: 3.7.3
* Operating System: Scientific Linux 7.9 (Nitrogen)

### Description

Hi Andre,
I recently started using SplAdder.
I was wondering if there is any straightforward way provided by SplAdder to classify as_events into either:

- **Annotated events**: present in the annotation (e.g. gtf) 
- **Novel events**: introduced during the graph augmentation step

Thanks in advance!

**Comment by akahles** [comment]
Dear @pablommesas ,

This is on my to-do list since quite a while and it is my plan to make the feature available with the next major release. I will leave this issue open and post here, once this has happened.

Best,

Andre

**Comment by akahles** [comment]
Dear @pablommesas ,

This functionality has been added with the latest release. Feedback is welcome. I am closing this for now. Please re-open, if there is an issue.

Best,

Andre

**Comment by pablommesas** [comment]
Dear Andre,

Thank you for this! I have tested the novel functionality, I think there might be something wrong with the implementation.
Overall there seems to be an exaggerated number of novel events, in my samples I found that ~80% of events were classified as novel.
For 'alt_3prime' events 100% of events were classified as novel which can't be.

Thanks!
