### ISSUE TITLE
Spladder work for Low read depth

### ISSUE THREAD

**Issue by OnkarMulay** [ratschlab/spladder#139]
* spladder version: latest
* Python version: 3.8
* Operating System: Ubuntu

```
Hi,

I have fastq files for a few samples with very low read depth. I wanted to know if Spladder works well on them to give good events?
Certainly, other tools don't perform well for samples with lower read depth.

Please let me know about your suggestions
```

**Comment by akahles** [comment]
Hi @OnkarMulay ,

Thank you for trying out SplAdder. Very low read depth is always tricky and it is hard for me to give an answer without having seen the data you are working with. As a general piece of advice, you can try to reduce the confidence level when running SplAdder. The default is 3 and you can try 2 or 1, which will lead to less filtering of the input reads. 
A second knob to turn is to optimise your read alignment step before running SplAdder, but this will only be helpful if a larger part of reads cannot be aligned (and hence is a factor in your low coverage).

Best,

Andre

PS: I am closing this for now, as it is not per se an issue in SplAdder. Please re-open if you still have concerns.

**Comment by OnkarMulay** [comment]
Yes, that's good. Thanks for the information, works for me
