### ISSUE TITLE
Additional dimension in `verified` dataset in `*counts.hdf5` files

### ISSUE THREAD

**Issue by pablommesas** [ratschlab/spladder#140]
* spladder version: v2.4.4
* Python version: 3.7.3
* Operating System: Scientific Linux 7.9 (Nitrogen)

### Description

Hi Andre,
I'm processing the data obtained from a SplAdder build run from 8 samples.
In particular, I'm interested in finding which events were found in which samples.

For this I'm using the `*counts.hdf5` files that contain the `verified` dataset, which according to the documentation contains: 

- _"bool matrix over events X samples that is 1 if an event was verified in a sample and 0 otherwise"_

In my case, this matrix has an additional dimension that seems to be event-specific. I'm not sure how to interpret these additional dimensions, and if any of those would contain the information I need (i.e. "is that event present in that particular sample").

Thanks in advance!

**Comment by pablommesas** [comment]
Thank you. This was very helpful!

**Comment by akahles** [comment]
I have added this to the documentation, which will become available with the next release. Will close this for now. Please re-open if necessary.
