### ISSUE TITLE
Spladder issues in test mode

### ISSUE THREAD

**Issue by OnkarMulay** [ratschlab/spladder#141]
* spladder version: 2.4.4
* Python version: 3.8.5
* Operating System: Unix

The build mode of the spladder was successful, it seems so. But have issues for test mode.
## Error log file
Traceback (most recent call last):
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/spladder_build.py", line 259, in spladder
    analyze_events(options, options.event_types[e_idx])
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/alt_splice/analyze.py", line 296, in analyze_events
    write_events_txt(fn_out_conf_txt, options.strains[sample_idx], events_all, fn_out_count, event_idx=confirmed_idx)
  File "/scratch/zq45/om4416/miniconda3/envs/Spladder/lib/python3.8/site-packages/spladder/alt_splice/write.py", line 90, in write_events_txt
    counts = event_counts_chunk[:, :, i - chunk_idx_event[0]]
IndexError: index 2901 is out of bounds for axis 2 with size 1725

ERROR: Testing mode can only be run on SplAdder outputs generated using the default merging strategy: --merge-strat merge_graphs

## Output file
Reporting complete exon_skip events:
Reporting confirmed exon_skip events:
writing exon_skip events in gff3 format to /scratch/zq45/om4416/Spladder_Eva_train/merge_graph_exon_skip_C3.confirmed.gff3
writing exon_skip events in flat txt format to /scratch/zq45/om4416/Spladder_Eva_train/merge_graph_exon_skip_C3.confirmed.txt.gz

## CODE

#!/bin/tcsh
#PBS -l walltime=30:00:00
#PBS -q normal
#PBS -l jobfs=1gb
#PBS -l mem=64gb
#PBS -l ncpus=48
#PBS -P zq45

conda activate /miniconda3/envs/Spladder

spladder build --bams /Spladder_bam.txt --annotation /Homo_sapiens.GRCh38.100.chr.gtf --merge-strat merge_graph --quantify-graph --qmode all --ignore-mismatches --outdir /Spladder_Eva_train

spladder test --conditionA /Eva_Spladder_bam1.txt --conditionB /Eva_Spladder_bam2.txt --outdir /Spladder_Eva_train

**Comment by akahles** [comment]
Hi @OnkarMulay ,

would you be able to share (part of) your data with me? It is hard to debug otherwise.

Thanks and Cheers,

Andre

**Comment by OnkarMulay** [comment]
How many samples will you need? It's bit big data. 3-4 samples would be around 16Gb.
But yeah, happy to share and get the issues solved, and then use Spladder and cite it. Thanks for the tool.

Let, me know how to share the sample

**Comment by akahles** [comment]
Hi @OnkarMulay ,

Thanks for being willing to share your data. Before we go there, there is one other question I would like to ask. In your above command, you write `--merge-strat merge_graph`. I think the option you want is `--merge-strat merge_graphs` (with an s in the end). Currently, providing an option as merge strategy that does not exist, will cause undefined behaviour. I have added it to my list to add a check that this not happens.

Can you please check whether the option you use is `merge_graph` or `merge_graphs`? You would need the latter.

Best,

Andre

**Comment by OnkarMulay** [comment]
Yes, you are correct. I'll close this issue now because I have made typing error. But issue comes again. I'll open new one.

Thanks,
Andre 👍
