### ISSUE TITLE
Conditions/Graph building 

### ISSUE THREAD

**Issue by herber4** [ratschlab/spladder#143]
If I am looking for splice differences between knockdown and controls, should I be building the splice graphs with the KD and controls? Also, would spladder be compatable with custom gtfs created from long reads?

Best, 

Austin

**Comment by akahles** [comment]
Dear @herber4 ,

Sorry for the late reply. If you are interested to test the differences between two conditions, it is best to build a joint graph with all samples, call events on the joint graph and then test for differential usage.

Regarding the GTF. You can use a custom built GTF, as long as it follows the GTF standard. SplAdder was designed using the GENCODE GTF standard and nomenclature (https://www.gencodegenes.org/pages/data_format.html) and works best with those files.

Best,

Andre

**Comment by akahles** [comment]
Dear @herber4 ,

I am closing this for now. Please re-open, if there are further questions.

Best,

Andre
