### ISSUE TITLE
RuntimeWarning: invalid value encountered in double_scalars

### ISSUE THREAD

**Issue by gtollefson** [ratschlab/spladder#144]
* spladder version: 2.4.4
* Python version:python/3.6.6
* Operating System: Unix

### Description

I've run the build and test commands for wildtype and mutant samples and receive an error during the test command with several Runtime warnings resulting in ValueError: zero-size array to reduction operation maximum which has no identity.

I've run the build steps for 3 wildtype and 3 mutant samples in a single command without error using a subset gtf file containing annotations for a single gene. (Side note: I also tried this workflow by running the build step separately for the wildtype and mutant alignment files and received the same end result) My command is as follows:

`spladder build -o data/gtollefs/gene_x_splicing_project/spladder/builds -b data/gtollefs/tpp1_splicing_project/star_alignment/SA23_analysis/H9-1_Aligned.out.sorted.bam,data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/H9-2_Aligned.out.sorted.bam,data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/H9-3_Aligned.out.sorted.bam,data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/SA23-1_Aligned.out.sorted.bam,data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/SA23-2_Aligned.out.sorted.bam,data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/SA23-3_Aligned.out.sorted.bam -a data/gtollefs/genomes/hg38/star_reference/hg38.gene_x.refGene.gtf --set-mm-tag Nm --ignore-mismatches`

I used the following custom parameters: I used the `--set-mm-tag Nm` option since my STAR aligned bam file contains tags in the `Nm:i:1` format. Despite this, the build command output still gave a warning and suggested using the --ignore-mismatches flag, which I added. I examined the bam file by eye and did not observe any lines missing the Nm tag and hope the reads with the tag aren't being ignored for some reason. 

Once I ran the build command, I ran the test command as follows:
`
spladder test --conditionA data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/H9-1_Aligned.out.sorted.bam,data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/H9-2_Aligned.out.sorted.bam,data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/H9-3_Aligned.out.sorted.bam --conditionB data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/SA23-1_Aligned.out.sorted.bam,data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/SA23-2_Aligned.out.sorted.bam,data/gtollefs/gene_x_splicing_project/star_alignment/SA23_analysis/SA23-3_Aligned.out.sorted.bam -a data/gtollefs/genomes/hg38/star_reference/hg38.gene_x.refGene.gtf --outdir data/gtollefs/gene_x_splicing_project/spladder/builds
`

The error message I received was:

> data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
>   out=out, **kwargs)
> data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in true_divide
>   ret, rcount, out=ret, casting='unsafe', subok=False)
> Traceback (most recent call last):
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/bin/spladder", line 11, in <module>
>     sys.exit(main())
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/spladder/spladder.py", line 190, in main
>     options.func(options)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/spladder/spladder_test.py", line 777, in spladder_test
>     (pvals, cov_used, disp_raw_used, disp_adj_used) = run_testing(cov, dmatrix0, dmatrix1, sf, options, event_type, test_idx)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/spladder/spladder_test.py", line 526, in run_testing
>     (disp_fitted, Lambda, disp_idx) = fit_dispersion(cov, disp_raw, (disp_raw_conv[:, 0] & test_idx)[:, np.newaxis], sf, options, dmatrix1, event_type)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/spladder/spladder_test.py", line 244, in fit_dispersion
>     modGamma = sm.GLM(disp_raw[idx], matrix, family=sm.families.Gamma(sm.families.links.identity()))
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/genmod/generalized_linear_model.py", line 314, in __init__
>     var_weights=var_weights, **kwargs)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/base/model.py", line 237, in __init__
>     super(LikelihoodModel, self).__init__(endog, exog, **kwargs)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/base/model.py", line 78, in __init__
>     **kwargs)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/base/model.py", line 101, in _handle_data
>     data = handle_data(endog, exog, missing, hasconst, **kwargs)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/base/data.py", line 673, in handle_data
>     **kwargs)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/base/data.py", line 87, in __init__
>     self._handle_constant(hasconst)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/base/data.py", line 131, in _handle_constant
>     exog_max = np.max(self.exog, axis=0)
>   File "<__array_function__ internals>", line 6, in amax
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
>     keepdims=keepdims, initial=initial, where=where)
>   File "data/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
>     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> ValueError: zero-size array to reduction operation maximum which has no identity

Can you help me to troubleshoot? Thank you in advance.

In case it's useful, I've pasted the entire output of the build command below:

> Augmenting splice graphs.
> =========================
> Generating splice graph ...
> ...done.
> 
> Loading introns from file ...
> ...done.
> 
> Filtering introns for ambiguity ...
> removed 21 of 37 (56.76 percent) introns overlapping to no or multiple genes
> ...done.
> 
> Testing for infeasible genes ...
> found 0 unfeasible genes
> ...done.
>  <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
> Inserting cassette exons ...
> 
> ... inserted 0 casette exons ....
> ... done.
> 
> Inserting intron retentions ...
> 
> ... inserted 0 new intron retentions ...
> ...done.
> 
> Inserting new intron edges ...
> ... chr chr11 - iteration 1/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 2/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 3/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 4/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 5/5
> 
> ... removing duplicate exons ...
> ... done.
> 
> Re-labeleling new alternative genes ...
> ... done.
> 
> Inserted:
> 	cassette_exon:	0
> 	intron_retention:	0
> 	intron_in_exon:	0
> 	alt_53_prime:	2
> 	exon_skip:	1
> 	gene_merge:	0
> 	new_terminal_exon:	0
> Saving genes to data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.H9-1_Aligned.out.sorted.pickle
> No pruning requested!
> Generating all isoforms not requested
> Augmenting splice graphs.
> =========================
> Generating splice graph ...
> ...done.
> 
> Loading introns from file ...
> ...done.
> 
> Filtering introns for ambiguity ...
> removed 20 of 40 (50.00 percent) introns overlapping to no or multiple genes
> ...done.
> 
> Testing for infeasible genes ...
> found 0 unfeasible genes
> ...done.
>  <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
> Inserting cassette exons ...
> 
> ... inserted 0 casette exons ....
> ... done.
> 
> Inserting intron retentions ...
> 
> ... inserted 0 new intron retentions ...
> ...done.
> 
> Inserting new intron edges ...
> ... chr chr11 - iteration 1/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 2/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 3/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 4/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 5/5
> 
> ... removing duplicate exons ...
> ... done.
> 
> Re-labeleling new alternative genes ...
> ... done.
> 
> Inserted:
> 	cassette_exon:	0
> 	intron_retention:	0
> 	intron_in_exon:	0
> 	alt_53_prime:	5
> 	exon_skip:	1
> 	gene_merge:	0
> 	new_terminal_exon:	1
> Saving genes to data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.H9-2_Aligned.out.sorted.pickle
> No pruning requested!
> Generating all isoforms not requested
> Augmenting splice graphs.
> =========================
> Generating splice graph ...
> ...done.
> 
> Loading introns from file ...
> ...done.
> 
> Filtering introns for ambiguity ...
> removed 18 of 37 (48.65 percent) introns overlapping to no or multiple genes
> ...done.
> 
> Testing for infeasible genes ...
> found 0 unfeasible genes
> ...done.
>  <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
> Inserting cassette exons ...
> 
> ... inserted 0 casette exons ....
> ... done.
> 
> Inserting intron retentions ...
> 
> ... inserted 0 new intron retentions ...
> ...done.
> 
> Inserting new intron edges ...
> ... chr chr11 - iteration 1/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 2/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 3/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 4/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 5/5
> 
> ... removing duplicate exons ...
> ... done.
> 
> Re-labeleling new alternative genes ...
> ... done.
> 
> Inserted:
> 	cassette_exon:	0
> 	intron_retention:	0
> 	intron_in_exon:	0
> 	alt_53_prime:	3
> 	exon_skip:	4
> 	gene_merge:	0
> 	new_terminal_exon:	1
> Saving genes to data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.H9-3_Aligned.out.sorted.pickle
> No pruning requested!
> Generating all isoforms not requested
> Augmenting splice graphs.
> =========================
> Generating splice graph ...
> ...done.
> 
> Loading introns from file ...
> ...done.
> 
> Filtering introns for ambiguity ...
> removed 23 of 44 (52.27 percent) introns overlapping to no or multiple genes
> ...done.
> 
> Testing for infeasible genes ...
> found 0 unfeasible genes
> ...done.
>  <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
> Inserting cassette exons ...
> 
> ... inserted 0 casette exons ....
> ... done.
> 
> Inserting intron retentions ...
> 
> ... inserted 0 new intron retentions ...
> ...done.
> 
> Inserting new intron edges ...
> ... chr chr11 - iteration 1/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 2/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 3/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 4/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 5/5
> 
> ... removing duplicate exons ...
> ... done.
> 
> Re-labeleling new alternative genes ...
> ... done.
> 
> Inserted:
> 	cassette_exon:	0
> 	intron_retention:	0
> 	intron_in_exon:	0
> 	alt_53_prime:	1
> 	exon_skip:	4
> 	gene_merge:	0
> 	new_terminal_exon:	4
> Saving genes to data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.SA23-1_Aligned.out.sorted.pickle
> No pruning requested!
> Generating all isoforms not requested
> Augmenting splice graphs.
> =========================
> Generating splice graph ...
> ...done.
> 
> Loading introns from file ...
> ...done.
> 
> Filtering introns for ambiguity ...
> removed 16 of 39 (41.03 percent) introns overlapping to no or multiple genes
> ...done.
> 
> Testing for infeasible genes ...
> found 0 unfeasible genes
> ...done.
>  <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
> Inserting cassette exons ...
> 
> ... inserted 1 casette exons ....
> ... done.
> 
> Inserting intron retentions ...
> 
> ... inserted 0 new intron retentions ...
> ...done.
> 
> Inserting new intron edges ...
> ... chr chr11 - iteration 1/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 2/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 3/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 4/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 5/5
> 
> ... removing duplicate exons ...
> ... done.
> 
> Re-labeleling new alternative genes ...
> ... done.
> 
> Inserted:
> 	cassette_exon:	1
> 	intron_retention:	0
> 	intron_in_exon:	0
> 	alt_53_prime:	4
> 	exon_skip:	4
> 	gene_merge:	0
> 	new_terminal_exon:	1
> Saving genes to data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.SA23-2_Aligned.out.sorted.pickle
> No pruning requested!
> Generating all isoforms not requested
> Augmenting splice graphs.
> =========================
> Generating splice graph ...
> ...done.
> 
> Loading introns from file ...
> ...done.
> 
> Filtering introns for ambiguity ...
> removed 19 of 43 (44.19 percent) introns overlapping to no or multiple genes
> ...done.
> 
> Testing for infeasible genes ...
> found 0 unfeasible genes
> ...done.
>  <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
> Inserting cassette exons ...
> 
> ... inserted 1 casette exons ....
> ... done.
> 
> Inserting intron retentions ...
> 
> ... inserted 0 new intron retentions ...
> ...done.
> 
> Inserting new intron edges ...
> ... chr chr11 - iteration 1/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 2/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 3/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 4/5
> 
> ... removing duplicate exons ...
> ... chr chr11 - iteration 5/5
> 
> ... removing duplicate exons ...
> ... done.
> 
> Re-labeleling new alternative genes ...
> ... done.
> 
> Inserted:
> 	cassette_exon:	1
> 	intron_retention:	0
> 	intron_in_exon:	1
> 	alt_53_prime:	4
> 	exon_skip:	4
> 	gene_merge:	0
> 	new_terminal_exon:	1
> Saving genes to data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.SA23-3_Aligned.out.sorted.pickle
> No pruning requested!
> Generating all isoforms not requested
> Loading data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.H9-1_Aligned.out.sorted.pickle ...
> ... done (1 / 6)
> Loading data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.H9-2_Aligned.out.sorted.pickle ...
> ... done (2 / 6)
> Processing ...
> . 0/1
> ... done
> 
> Loading data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.H9-3_Aligned.out.sorted.pickle ...
> ... done (3 / 6)
> Processing ...
> . 0/1
> ... done
> 
> Loading data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.SA23-1_Aligned.out.sorted.pickle ...
> ... done (4 / 6)
> Processing ...
> . 0/1
> ... done
> 
> Loading data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.SA23-2_Aligned.out.sorted.pickle ...
> ... done (5 / 6)
> Processing ...
> . 0/1
> ... done
> 
> Loading data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.SA23-3_Aligned.out.sorted.pickle ...
> ... done (6 / 6)
> Processing ...
> . 0/1
> ... done
> 
> Store genes at: data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.merge_graphs.pickle
> 
> 1/6
> genes: 1
> 
> sample 1/1
> 
> counting 1 genes on contig chr11
> .
> 2/6
> genes: 1
> 
> sample 1/1
> 
> counting 1 genes on contig chr11
> .
> 3/6
> genes: 1
> 
> sample 1/1
> 
> counting 1 genes on contig chr11
> .
> 4/6
> genes: 1
> 
> sample 1/1
> 
> counting 1 genes on contig chr11
> .
> 5/6
> genes: 1
> 
> sample 1/1
> 
> counting 1 genes on contig chr11
> .
> 6/6
> genes: 1
> 
> sample 1/1
> 
> counting 1 genes on contig chr11
> .
> confidence 3 / sample 0
> Loading gene structure from data/gtollefs/gene_x_splicing_project/spladder/builds/spladder/genes_graph_conf3.merge_graphs.pickle ...
> ... done.
> 
> Remove 0-length intron events
> 
> Make intron_retention events unique by strain
> events dropped: 0
> 
> Make intron_retention events unique by event
> events dropped: 0
> saving intron retentions to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_intron_retention_C3.pickle
> 
> Remove 0-length intron events
> 
> Make exon_skip events unique by strain
> events dropped: 0
> 
> Make exon_skip events unique by event
> events dropped: 2
> saving exon skips to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_exon_skip_C3.pickle
> 
> Remove 0-length intron events
> 
> Make mult_exon_skip events unique by strain
> events dropped: 0
> 
> Make mult_exon_skip events unique by event
> events dropped: 0
> saving multiple exon skips to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_mult_exon_skip_C3.pickle
> 
> Remove 0-length intron events
> 
> Make alt_5prime events unique by strain
> events dropped: 0
> 
> Make alt_5prime events unique by event
> events dropped: 0
> Corrected 0 events
> Removed 0 events
> saving alt 5 prime events to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_alt_5prime_C3.pickle
> 
> Remove 0-length intron events
> 
> Make alt_3prime events unique by strain
> events dropped: 0
> 
> Make alt_3prime events unique by event
> events dropped: 1
> Corrected 0 events
> Removed 0 events
> saving alt 3 prime events to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_alt_3prime_C3.pickle
> saving mutually exclusive exons to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_mutex_exons_C3.pickle
> analyzing events with confidence 3
> .................
> Reporting complete exon_skip events:
> 
> Reporting confirmed exon_skip events:
> writing exon_skip events in gff3 format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_exon_skip_C3.confirmed.gff3
> writing exon_skip events in flat txt format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_exon_skip_C3.confirmed.txt.gz
> analyzing events with confidence 3
> ..
> Reporting complete intron_retention events:
> 
> Reporting confirmed intron_retention events:
> writing intron_retention events in gff3 format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_intron_retention_C3.confirmed.gff3
> writing intron_retention events in flat txt format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_intron_retention_C3.confirmed.txt.gz
> analyzing events with confidence 3
> ..............
> Reporting complete alt_3prime events:
> 
> Reporting confirmed alt_3prime events:
> writing alt_3prime events in gff3 format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_alt_3prime_C3.confirmed.gff3
> writing alt_3prime events in flat txt format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_alt_3prime_C3.confirmed.txt.gz
> analyzing events with confidence 3
> ......
> Reporting complete alt_5prime events:
> 
> Reporting confirmed alt_5prime events:
> writing alt_5prime events in gff3 format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_alt_5prime_C3.confirmed.gff3
> writing alt_5prime events in flat txt format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_alt_5prime_C3.confirmed.txt.gz
> analyzing events with confidence 3
> .....
> Reporting complete mult_exon_skip events:
> 
> Reporting confirmed mult_exon_skip events:
> writing mult_exon_skip events in gff3 format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_mult_exon_skip_C3.confirmed.gff3
> writing mult_exon_skip events in flat txt format to data/gtollefs/gene_x_splicing_project/spladder/builds/merge_graphs_mult_exon_skip_C3.confirmed.txt.gz
> analyzing events with confidence 3
> 
> No mutex_exons event could be found. - Nothing to report

**Comment by gtollefson** [comment]
@akahles I would like to follow up on my issue post above.

**Comment by gtollefson** [comment]
I noticed that I had accidentally set `--set-mm-tag Nm` incorrectly and that it should have been `--set-mm-tag nM`. Rerunning without --ignore-mismatches produced more AS events reported in the build step however when I run `test` I receive the error: 

> RuntimeWarning: invalid value encountered in double_scalars

I've pasted the complete output below and have looked inside `genes_graph_conf3.merge_graphs.count.hdf5` and have pasted the output below. It looks like several counts have shape 1/1 as the second value.

genes_graph_conf3.merge_graphs.count.hdf5 contents:

> findiv13vhb733:spladder George$ h5ls -v genes_graph_conf3.merge_graphs.count.hdf5 
> Opened "genes_graph_conf3.merge_graphs.count.hdf5" with sec2 driver.
> edge_idx                 Dataset {55/55}
>     Location:  1:23168
>     Links:     1
>     Storage:   440 logical bytes, 440 allocated bytes, 100.00% utilization
>     Type:      native double
> edges                    Dataset {55/55, 12/12}
>     Location:  1:21904
>     Links:     1
>     Storage:   5280 logical bytes, 5280 allocated bytes, 100.00% utilization
>     Type:      native double
> gene_ids_edges           Dataset {55/55, 1/1}
>     Location:  1:22176
>     Links:     1
>     Storage:   440 logical bytes, 440 allocated bytes, 100.00% utilization
>     Type:      native long
> gene_ids_segs            Dataset {100/100, 1/1}
>     Location:  1:21632
>     Links:     1
>     Storage:   800 logical bytes, 800 allocated bytes, 100.00% utilization
>     Type:      native long
> gene_names               Dataset {1/1, 1/1}
>     Location:  1:22896
>     Links:     1
>     Storage:   15 logical bytes, 15 allocated bytes, 100.00% utilization
>     Type:      15-byte null-padded ASCII string
> seg_len                  Dataset {100/100, 1/1}
>     Location:  1:22624
>     Links:     1
>     Storage:   800 logical bytes, 800 allocated bytes, 100.00% utilization
>     Type:      native long
> seg_pos                  Dataset {100/100, 12/12}
>     Location:  1:1672
>     Links:     1
>     Storage:   9600 logical bytes, 9600 allocated bytes, 100.00% utilization
>     Type:      native double
> segments                 Dataset {100/100, 12/12}
>     Location:  1:1400
>     Links:     1
>     Storage:   9600 logical bytes, 9600 allocated bytes, 100.00% utilization
>     Type:      native double
> strains                  Dataset {12/12}
>     Location:  1:800
>     Links:     1
>     Storage:   384 logical bytes, 384 allocated bytes, 100.00% utilization
>     Type:      32-byte null-padded ASCII string


Error:

> /gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/genmod/generalized_linear_model.py:798: RuntimeWarning: invalid value encountered in double_scalars
>   return np.sum(resid / self.family.variance(mu)) / self.df_resid
> Traceback (most recent call last):
>   File "/gtollefs/gene_x_splicing_project/spladder/venv/bin/spladder", line 11, in <module>
>     sys.exit(main())
>   File "/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/spladder/spladder.py", line 190, in main
>     options.func(options)
>   File "/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/spladder/spladder_test.py", line 777, in spladder_test
>     (pvals, cov_used, disp_raw_used, disp_adj_used) = run_testing(cov, dmatrix0, dmatrix1, sf, options, event_type, test_idx)
>   File "/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/spladder/spladder_test.py", line 526, in run_testing
>     (disp_fitted, Lambda, disp_idx) = fit_dispersion(cov, disp_raw, (disp_raw_conv[:, 0] & test_idx)[:, np.newaxis], sf, options, dmatrix1, event_type)
>   File "/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/spladder/spladder_test.py", line 245, in fit_dispersion
>     res = modGamma.fit()
>   File "/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1065, in fit
>     cov_kwds=cov_kwds, use_t=use_t, **kwargs)
>   File "/gtollefs/gene_x_splicing_project/spladder/venv/lib/python3.6/site-packages/statsmodels/genmod/generalized_linear_model.py", line 1179, in _fit_irls
>     raise ValueError("The first guess on the deviance function "
> ValueError: The first guess on the deviance function returned a nan.  This could be a boundary  problem and should be reported.

**Comment by akahles** [comment]
Dear @gtollefson ,

sorry for the late reply. Could you please run `spladder test` in verbose mode (`-v`) and post the log up to the error message?

Thannks,

Andre

**Comment by akahles** [comment]
Dear @gtollefson ,

I am closing this for now. Please re-open, if the issue still persists and you can provide further information.

Best,

Andre
