### ISSUE TITLE
Different info between "test_results" and "gff3"

### ISSUE THREAD

**Issue by minnie0121** [ratschlab/spladder#158]
* spladder version:3.0.2
* Python version:3.9.7
* Operating System:Linux

### Description

I found the chromosome numbers and exon positions were different between the result of "build mode" (gff3) and  "test mode" (tsv).
Considering the Ensembl Gene ID in each file is the same, the information in the gff3 is probably true.
Please let me know the cause of this difference and the effect for the test results.
```
"test_results_extended_C3_exon_skip.tsv"
event_id        chrm    exon_pos        alt_usage       gene_id gene_name
exon_skip.129637        7       151235047-151235628:151236407-151236795:151237373-151237593     0:1:0   ENSG00000012817 KDM5D
```

```
"merge_graphs_exon_skip_C3.confirmed.gff3"
Y       exon_skip       gene    19741318        19743239        .       -       .       ID=exon_skip.129637;GeneName="ENSG00000012817";HasNovelJunction="N"
Y       exon_skip       mRNA    19741318        19743239        .       -       .       ID=exon_skip.129637_iso1;Parent=exon_skip.129637;GeneName="ENSG00000012817";HasNovelJunction="N"
Y       exon_skip       exon    19741318        19741488        .       -       .       Parent=exon_skip.129637_iso1
Y       exon_skip       exon    19743162        19743239        .       -       .       Parent=exon_skip.129637_iso1
Y       exon_skip       mRNA    19741318        19743239        .       -       .       ID=exon_skip.129637_iso2;Parent=exon_skip.129637;GeneName="ENSG00000012817";HasNovelJunction="N"
Y       exon_skip       exon    19741318        19741488        .       -       .       Parent=exon_skip.129637_iso2
Y       exon_skip       exon    19741735        19741857        .       -       .       Parent=exon_skip.129637_iso2
Y       exon_skip       exon    19743162        19743239        .       -       .       Parent=exon_skip.129637_iso2
```

### What I Did

I performed SplAdder "build mode" according to "Use on large cohorts" page (https://spladder.readthedocs.io/en/latest/spladder_cohort.html), then ran "test mode" using 3 samples for each group.

```
spladder test \
 --conditionA "${control_sample}" \
 --conditionB "${compare_sample}" \
 --labelA "${control_group}" \
 --labelB "${compare_group}" \
 --outdir "${spladder_dir}" \
 -v
```

**Comment by kevinigfl** [comment]
I obtain the same discrepancy, did you fix the bug?

**Comment by jamie-lyu** [comment]
Also I am suffering from the same issue.

**Comment by jbendik14** [comment]
I have been having the exact same issue. Did anyone ever find a solution/reason for this?

**Comment by kevinigfl** [comment]
Hi, I did not find the reason, but a solution is to take the event_id identified in the test files and go back to the build files where the positions (chr-start-end) are correct.
Hope it can help

**Comment by michael-kotliar** [comment]
Got the same problem. Completely unreliable tool if such simple errors occur.

**Comment by akahles** [comment]
This should be fixed with the latest release. Please re-open if you find otherwise.
