### ISSUE TITLE
Running too slow!

### ISSUE THREAD

**Issue by ifreeman6** [ratschlab/spladder#164]
* spladder version:  3.0.2
* Python version:  3.8.2
* Operating System: Linux

### Description
Dear Andre:
When I tried to run 20 samples, which need about 3~4 days. The speed is so slow. I still have many samples to run, so I want to know how to speed up this programming. 
The following is my bash script, I set 20 parallels :
```shell
gtfDir=gencode.v19.annotation.nochr.gtf
bam_path=bam_list.txt
output=/path/to/spladder
spladder build -o $output -b $bam_path -a $gtfDir --parallel 20 --set-mm-tag nM

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by wuzhigui** [comment]
Hello， I am the same  with you !
but , I have another error ,could you help me ?
![image](https://user-images.githubusercontent.com/70992194/165048399-63c8c11f-b24d-4f66-9161-8f802af61464.png)
That is quite worry me !

**Comment by akahles** [comment]
Thank you for your feedback

For large cohorts, we recommend running in parallel across several machines:
https://spladder.readthedocs.io/en/latest/spladder_cohort.html

Other than that, I also recommend using `--sparse-bam`. This will pre-parse your alignment files and should greatly speed up the process of event calling and quantification. 

Regarding the issue of no output events, I'd recommend lowering the confidence level (from the default 3) to 2 or 1.

Please re-open, if you think the issue still persists.

Best,

Andre
