### ISSUE TITLE
Viz test not working 

### ISSUE THREAD

**Issue by spazm5** [ratschlab/spladder#165]
* spladder version: 3.0.2
* Python version: 3.6.15
* Operating System: Linux

### Description
Dear Andre,
I'm trying to visualize my test results, still trying to figure out how to visualize differentially expressed isoforms of a specific gene, but for the time being just want to see the top 5. However, I keep getting this error:
"ERROR: provided gene ID "chr12" could not be found, please check for correctness"

### What I Did
spladder viz --test default exon_skip 5\
             --track splicegraph \
             --confidence 2 \
             -o ./spladder_out2

Thanks in advance, 
Sean
```

**Comment by Tina610** [comment]
I also encountered a similar problem, have you solved it？ths

**Comment by akahles** [comment]
Dear @spazm5 ,

Thanks a lot for reporting and sorry for the late reply. I somehow managed not to get notifications for this repo. The bug was introduced with the latest release. I have found it and will re-release soon.

Best,

Andre
