### ISSUE TITLE
Spladder accuracy for samples with high multimappers

### ISSUE THREAD

**Issue by tbrunetti** [ratschlab/spladder#167]
* spladder version: 2.4.4
* Python version: 3.9
* Operating System: Ubuntu 18.04

### Description

Thank you for this wonderful tool!  I have a general question regarding spladder's generation of splice graphs where uniquely mapped and multimapped reads across samples varies.  We are have reproducibility issues within biological replicates.  I know we do not have enough samples to get a stable variance measurement since one biological group only has 2 bio reps, and the other biological group only has 3 bio reps.  

However, I am curious, would we get better splice graphs if we only use the uniquely mapped reads output by STAR and remove the multimappers?  How does spladder handle multimapped alignments when constructing a splice graph?  I see in the docs, by default spladder only uses the primary alignment, however, the primary alignment is still a multimapper, so would it be better to just use uniquely mapped reads?

Thanks!

**Comment by akahles** [comment]
Thank you for reaching out. SplAdder currently does not make a distinction between unique- and multi-mappers. It will default to the primary alignment, but not discard multimappers. If you would like to ignore multi-mappers for now, I'd suggest to pre-filter your STAR alignments. For instance, you can just get the unique mappers via:
```
samtools view <bamfile> -d NH:1
```

**Comment by tbrunetti** [comment]
Thank you for your response!  Yes, I ended up just using the unique alignments for now.  Thanks!
