### ISSUE TITLE
parallelization of SplAdder

### ISSUE THREAD

**Issue by akesarwani** [ratschlab/spladder#17]
Hi, 
I have about 200 BAM files, which would require huge RAM and long time if supplied together to SplAdder for splicing analysis. I was wondering if SplAdder run with individual BAM could be combined for this purpose. Do you have any suggestion about handling large number of dataset. Thanks.

**Comment by akahles** [comment]
Sorry for the late reply. I was traveling and am working through the issues now. There are several ways to parallelize SplAdder, either using multiple cores or distributing jobs over multiple compute nodes. However, both are still experimental and are currently tuned to the compute environment I have available here. I will add a section to the wiki next week that discusses how to handle a larger set of files.
