### ISSUE TITLE
TypeError: object of type 'Gene' has no len()

### ISSUE THREAD

**Issue by MB571** [ratschlab/spladder#177]
* spladder version: 3.0.3
* Python version: python-3.9.12
* Operating System: linux (HPC)

When running Spladder build i get the recurring error at the end of the analysis, in the remove short exons phase stating 
"line 70, in remove_short_exons 
keep_idx = np.where(~np.in1d(np.arange(len(genes[i])), rm_idx))[0] 
TypeError: object of type 'Gene' has no len()"

Would anyone know what could be causing this?

```

```

**Comment by akahles** [comment]
Thanks @MB571 for reporting this. I have identified the bug and pushed a fix to the development branch. Will make this available with the next release.

**Comment by akahles** [comment]
This fix is now available in the latest release, please reopen if this still causes problems.
