### ISSUE TITLE
Spladder error loading introns

### ISSUE THREAD

**Issue by cgrisdale** [ratschlab/spladder#18]
Hi,

I'm running into some errors while trying to run Spladder. I'm using a Cufflinks-created gtf because I work on a non-model system. I'm not sure if the error is related to my GTF, but just in case, this is what it looks like:

scaffold_1      Cufflinks       transcript      12      412     1000    .       .       gene_id "CUFF.1"; transcript_id "CUFF.1.1"; FPKM "0.8222662114"; frac "1.000000"; conf_lo "0.471651"; conf_hi "1.172882"; cov "7.148884";
scaffold_1      Cufflinks       exon    12      412     1000    .       .       gene_id "CUFF.1"; transcript_id "CUFF.1.1"; exon_number "1"; FPKM "0.8222662114"; frac "1.000000"; conf_lo "0.471651"; conf_hi "1.172882"; cov "7.148884";
scaffold_1      Cufflinks       transcript      31940   35734   1000    .       .       gene_id "CUFF.2"; transcript_id "CUFF.2.1"; FPKM "3.1558882615"; frac "1.000000"; conf_lo "2.937705"; conf_hi "3.374071"; cov "35.466206";
scaffold_1      Cufflinks       exon    31940   35734   1000    .       .       gene_id "CUFF.2"; transcript_id "CUFF.2.1"; exon_number "1"; FPKM "3.1558882615"; frac "1.000000"; conf_lo "2.937705"; conf_hi "3.374071"; cov "35.466206";

The error message I got is:

Generating splice graph ...
...done.
Loading introns from file ...
Traceback (most recent call last):
  File "/home/cameron/Programs/spladder-master/python/spladder.py", line 255, in <module>
    spladder()
  File "/home/cameron/Programs/spladder-master/python/spladder.py", line 180, in spladder
    spladder_core(CFG)
  File "/home/cameron/Programs/spladder-master/python/modules/core/spladdercore.py", line 26, in spladder_core
    genes = gen_graphs(genes, CFG)
  File "/home/cameron/Programs/spladder-master/python/modules/core/gen_graphs.py", line 82, in gen_graphs
    introns = get_intron_list(genes, CFG)
  File "/home/cameron/Programs/spladder-master/python/modules/reads.py", line 336, in get_intron_list
    chunks = sp.array([[CFG['chrm_lookup'][x.chr], strands.index(x.strand), x.start, x.stop] for x in genes], dtype = 'int')
ValueError: '.' is not in list

The command I ran:
python ~/Programs/spladder-master/python/spladder.py -a ~/Programs/Cufflinks.gtf -b ../tophat.sorted.bam -o ./spladder_out

Also, I'm getting this warning message (repeatedly). I'm assuming this is because of the format of the Cufflinks GTF file. Will this cause any issues?
WARNING: /home/cameron/Cufflinks.gtf does not have gene level information for transcript CUFF.33832.1 - information has been inferred from tags

Any advise you could provide would be much appreciated.

Thanks,

Cam

**Comment by akahles** [comment]
Hi Cam,
Sorry for the late reply - I was traveling the past weeks and am still working through my backlog. 

SplAdder expects the input GTF to have a strand value set (either +/-). I will add to my TODO list to provide a more useful error message if the strand field is missing.

If you add the strand information to your GTF it should work. Please let me know if you find otherwise.

**Comment by akahles** [comment]
Please re-open, if error should still persist.

**Comment by jfass** [comment]
I've been seeing this, in both the recent spladder and 1.2.1. My gtf looks like:

```
chr1    hg19_refGene    exon    176153769       176153828       0.000000        -       .       gene_id "NM_022457"; transcript_id "NM_022457"; 
chr1    hg19_refGene    CDS     176175708       176176114       0.000000        -       0       gene_id "NM_022457"; transcript_id "NM_022457"; 
chr1    hg19_refGene    start_codon     176176112       176176114       0.000000        -       .       gene_id "NM_022457"; transcript_id "NM_022457"; 
chr1    hg19_refGene    exon    176175708       176176380       0.000000        -       .       gene_id "NM_022457"; transcript_id "NM_022457"; 
chr1    hg19_refGene    exon    184356150       184356502       0.000000        +       .       gene_id "NM_030806"; transcript_id "NM_030806"; 
chr1    hg19_refGene    start_codon     184446644       184446646       0.000000        +       .       gene_id "NM_030806"; transcript_id "NM_030806"; 
chr1    hg19_refGene    CDS     184446644       184446737       0.000000        +       0       gene_id "NM_030806"; transcript_id "NM_030806"; 
```

... so, strand is set, yah? Could this be related to the fact that the gene_id's and transcript_id's have all been set to match each other?

Thx,
~Joe
