### ISSUE TITLE
Double-booked exons 

### ISSUE THREAD

**Issue by trebbiano** [ratschlab/spladder#19]
SplAdder produces the following error when using annotations with exons assigned to multiple genes:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

at the step 'Make alt_3prime events unique by strain'
As discussed, this will require SplAdder to select one of the alternative genes claiming the same exon. I am adding this post to keep track of this issue. 

Thanks!

**Comment by akahles** [comment]
I added a preprocessing step to filter out genes that share at least one exact exon. A list of affected genes is stored, so the user can modify the annotation if necessary. SplAdder will ignore these genes otherwise. I believe this should fix the above issue. If not, please re-open.
