### ISSUE TITLE
e2_cov_region in intron_retention output

### ISSUE THREAD

**Issue by perllb** [ratschlab/spladder#199]
* spladder version: 3.0.5
* Python version: 3.9
* Operating System: ubuntu

### Description

According to these docs: https://spladder.readthedocs.io/en/latest/file_formats.html#output-files-build-mode
Intron retention output file should contain `e2_cov_region: fraction of positions in the intron that have a coverage > 0`
However, my IR output files do not have this column.

### What I Did

```
spladder build \
          --bams input.bam \
          --ase-edge-limit 200 \
          --annotation input.gtf \
          --outdir output \
          --readlen 150 \
          --confidence 1 \
          --event-types exon_skip,alt_3prime,alt_5prime,mult_exon_skip,intron_retention \
          --ignore-mismatches
```

**Comment by akahles** [comment]
Thanks a lot for reporting - this should be fixed now with release version 3.1.0
