### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by akesarwani** [ratschlab/spladder#2]
Hi Andre,
I was wondering if there is any manual or example about how to use spladder. Your response is highly appreciated.

**Comment by akahles** [comment]
The user interface has been changed over the past months. I am currently writing a how to, which will be made available here very shortly (within the next week). I will let you know once this is available.

**Comment by akahles** [comment]
I have added more documentation to the matlab version. Documentation for the python version will follow shortly. I am happy about any feedback.

**Comment by akahles** [comment]
I will close this for now. Please reopen, if you feel this issue has not been resolved in a sufficient way.

**Comment by kmhernan** [comment]
In relation to this, could you possibly provide an example of how you used rDiff to test for differences? I would appreciate it!

**Comment by akahles** [comment]
This is a very good suggestion. I will work to add this soon. Re-open this for now.

**Comment by kmhernan** [comment]
Thanks! I am running into the issue of having many tumor-normal pairs and wondering if it's possible to run each pair separately and somehow merge everything at the end? The memory consumption for a single pair was almost 30GB and took about 12 hours, I'm a bit worried about trying to run all of them at once. So any information about this situation would be very useful! Thanks again.

**Comment by akahles** [comment]
Just to confirm. You talk about possible parallelizations of rDiff or of SplAdder?

**Comment by kmhernan** [comment]
I guess so. I am only on the SplAdder part and am not familiar with rDiff. I know you support some kind of parallelization, but I'm using PBS/Torque. If I could do some scatter-gather on my own I would be satisfied. I just am not sure of the appropriate steps to take to do this.

**Comment by akahles** [comment]
Ok, SplAdder parallelization is still somewhat experimental, but at least I tested it here with torque, so you could give it a try. But as I said, I never tested it in the wild. However, I will augment the documentation in the next days.

**Comment by pengchy** [comment]
Hi kahles,

I don't understand the .cpickle format, how to convert the annotation in gtf format to cpickle format?

    -a FILE, --annotation=FILE
                        annotation file name (annotation in *.cpickle format)

**Comment by akahles** [comment]
Dear pengchy,

SplAdder takes annotations in GTF or GFF3 format. The statement in the parameter description is wrong. I have updated (and reorganized) the parameter description. 
Thank you very much for making me aware of this.

Best,

Andre

**Comment by akahles** [comment]
A more up to date documentation is now available on readthedocs (https://spladder.readthedocs.io/). I will close this issue for now. Please open a new issue, if further questions arise.
