### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by armin-github** [ratschlab/spladder#26]
Hi,
I installed the script and the test with the example files completes successfully. But, I get the following error when I run the script using my own (.gff3 and .bam) files:
###### 

... init structure
Traceback (most recent call last):
  File "spladder.py", line 265, in <module>
    spladder()
  File "spladder.py", line 143, in spladder
    (genes, CFG) = init.init_genes_gff3(CFG['anno_fname'], CFG, CFG['anno_fname'] + '.pickle')
  File "/home/ntatto/spladder-master/python/modules/init.py", line 191, in init_genes_gff3
    tags = get_tags_gff3(sl[8])
IndexError: list index out of range
###### 

I would appreciate it very much if you could help with this issue.

**Comment by akahles** [comment]
Hi,
Could you please send me the first couple of lines of your gff3 file? It seems that the annotation does not have the format that SplAdder expects.

Thanks,
Andre

**Comment by armin-github** [comment]
Hi Andre,Thank you for your response. Yes, there were fasta sequences at the bottom of the gff3 file. After I removed them, it proceeded with the analysis, but it now stops later on with the following output and error message:=========================Generating splice graph ...
Total genes: 5149Total genes with alternative isoforms: 6Total genes alternatively spliced: 6Total constitutively spliced: 5143Traceback (most recent call last):  File "spladder.py", line 265, in <module>    spladder()  File "spladder.py", line 184, in spladder    spladder_core(CFG)  File "/home/ntatto/spladder-master/python/modules/core/spladdercore.py", line 21, in spladder_core    genes = gen_graphs(genes, CFG)  File "/home/ntatto/spladder-master/python/modules/core/gen_graphs.py", line 63, in gen_graphs    genes[i].start = min([x.min() for x in genes[i].exons])ValueError: min() arg is an empty sequence
Could you perhaps help us what the reason for this might be? 
Thank you in advance!
Armin

 

    On Sunday, February 28, 2016 1:53 AM, Andre Kahles <notifications@github.com> wrote:
 

 Hi,
Could you please send me the first couple of lines of your gff3 file? It seems that the annotation does not have the format that SplAdder expects.Thanks,
Andre—

**Comment by akahles** [comment]
It still looks like the annotation is not parsed correctly. Does your annotation contain genes that have no exons annotated?

**Comment by armin-github** [comment]
My gff file has protein coding genes and tRNA/rRNAs. The features present for a protein-coding gene are: gene, CDS, mRNA and exon. The features for a tRNA or rRNA gene are: gene, exon, and tRNA/rRNA. For example:FR839632        GenBank exon    2573    2643    .       +       .       Parent=tRNA-Met2.r01;gene=tRNA-Met2;locus_tag=PP7435_Mit-0030
FR839632        GenBank gene    2943    3191    .       +       .       ID=ND4L;Name=ND4L;gene=ND4L;locus_tag=PP7435_Mit-0035
FR839632        GenBank mRNA    2943    3191    .       +       .       ID=ND4L.t01;Name=ND4L.t01;Parent=ND4L
FR839632        GenBank CDS     2943    3191    .       +       0       ID=ND4L.p01;Name=ND4L.p01;...###########################tRNA gene:FR839632        GenBank exon    3191    5119    .       +       .       Parent=ND5.t01
FR839632        GenBank gene    5322    5392    .       +       .       ID=tRNA-Gly;Name=tRNA-Gly;gene=tRNA-Gly;locus_tag=PP7435_Mit-0045
FR839632        GenBank tRNA    5322    5392    .       +       .       ID=tRNA-Gly.r01;...
#####################Are there any restrictions implemented in the script for parsing gff files? Should I change anything?Sincerely,Armin
 

    On Tuesday, March 1, 2016 4:28 PM, Andre Kahles <notifications@github.com> wrote:
 

 It still looks like the annotation is not parsed correctly. Does your annotation contain genes that have no exons annotated?—

**Comment by akahles** [comment]
Hi Armin, would it be possible that you share your annotation file with me or point me to a location where I could download it. The given examples do not provide enough information to resolve the issue. I appreciate your help.
Thanks, Andre

**Comment by akahles** [comment]
Please re-open if this problem still occurs.
