### ISSUE TITLE
ImportError: No module named diagnose

### ISSUE THREAD

**Issue by rschulzUK** [ratschlab/spladder#30]
hi Andre,

just ran into this error, trying for the first time to run the test module (w/ both master and development branch):
```
rschulz@noris:~/bin/spladder-development/python$ python spladder_test.py 
Traceback (most recent call last):
  File "spladder_test.py", line 22, in <module>
    import modules.viz.diagnose as plot
ImportError: No module named diagnose
```

any help much appreciated, Reiner

**Comment by akahles** [comment]
Some changes got lost in between some branch merges. Sorry about that. Should be fixed now in both master and development branches. Please re-open if still persistent.
