### ISSUE TITLE
over-counting in genes_graph_conf2.merge_graphs.gene_exp.hdf5

### ISSUE THREAD

**Issue by rschulzUK** [ratschlab/spladder#33]
Hi Andre,

Since spladder produces gene-level counts, I thought I would use them as input to DESeq2, limma etc. to identify DEGs. Overall, the results made sense for the HIV data set I am looking at (eg, up-regulation of Interferon-inducible genes). But when I compared spladder counts with summarizeOverlap counts (from GenomicAlignments Bioconductor package), I found genes for which spladder over-counts. I attach a spreadsheet with a count comparison for human Chr 7. Spladder counts are overall greater by a factor of 2x, which is the result of counting reads rather than fragments. But there also are cases where the spladder count is greater by orders of magnitude. I have highlighted a particular case: ENST00000390416 (TRBJ2-4). Spladder gives a count of ~100,000 across the five samples, versus a summarizeOverlap count of ~100. The spladder count concurs with what `samtools view` outputs for the region corresponding to ENST00000390416. However, the vast majority of the alignments contain a splice junction, i.e., an intron of another gene that contains ENST00000390416. samtools is not splice-aware so that I understand its count. Are the spladder counts in *.merge_graphs.gene_exp.hdf5 meant to take into account splicing? If not, then my observation is not really an issue.

Best, Reiner
[counts.7.ods.zip](https://github.com/ratschlab/spladder/files/253975/counts.7.ods.zip)

**Comment by akahles** [comment]
Hi Reiner,
Thank you for the detailed report. Is my understanding correct that the introns fully spans over ENST00000390416? In this case SplAdder should indeed not count these reads towards the expression of ENST00000390416. Could you maybe provide me with a small example dataset that I could use to reproduce the counting issue? A slice from the bam file of  the specific region would be sufficient. 

Thanks and Cheers,
Andre

**Comment by akahles** [comment]
I think I have found a way to reproduce this. I'll keep you posted whether I need more information.

**Comment by rschulzUK** [comment]
Have sent you a private mail with link to example dataset.

**Comment by akahles** [comment]
Hi Reiner, I further looked into the case and both my example file as your examples file (although mapped to different references -- hg19 vs hg38) produce the same result. The count is not a clear artifact, although I am not quite decided on how to handle this case in future. 

What happens is the following. In the input alignment, there is quite a number of spliced reads that connect the end of TRBJ2-4 (ENSG00000211768) to the beginning of TRBC2 (ENSG00000211772). That is, parts of TRBC2 are then also counted as TRBJ2-4. When one of them is very highly expressed (as is true for TRBC2) this biases the average expression count of the other gene.

What I will most probably do in the future is to replace the two single genes with a merged version, so the user can see that this is not the original genes that have been annotated. I will write it on my ToDo list, but this might take some time to get fully resolved in the code.

Thank you for sending over the data to get this figured out and confirmed.

Cheers,
Andre

**Comment by akahles** [comment]
In the latest version of SplAdder, these connection cases should no longer occur, as introns connecting multiple genes are filtered out. Please open a new issue if this should still be a problem.
