### ISSUE TITLE
spladder_test.py error unless sample order is the same as for spladder.py

### ISSUE THREAD

**Issue by rschulzUK** [ratschlab/spladder#35]
To illustrate, below spladder.py is called with the sample order Control1, Control2, HIV1, HIV2, HIV3:
```
SPLADDER_HOME=/home/rschulz/bin/spladder-1.0.0/python/
CHR=Y

mkdir -p ./output_${CHR}

python $SPLADDER_HOME/spladder.py \
-a ./input/gencode.v24.annotation.$CHR.gff3 \
-b ./input/bam/Control1.$CHR.bam,./input/bam/Control2.$CHR.bam,./input/bam/HIV1.$CHR.bam,./input/bam/HIV2.$CHR.bam,./input/bam/HIV3.$CHR.bam \
-n 101 \
-o ./output_${CHR} \
-v y \
-c 2 \
-M merge_graphs \
-t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip \
> ./output_${CHR}/spladder.log 2>&1
```
If spladder_test.py is called to compare HIV1, HIV2, HIV3 with Control1, Control2, the result is an index error:
```
SPLADDER_HOME=/home/rschulz/bin/spladder/python/
CHR=Y

python $SPLADDER_HOME/spladder_test.py \
-a HIV1.$CHR,HIV2.$CHR,HIV3.$CHR \
-b Control1.$CHR,Control2.$CHR \
-n 101 \
-o ./output_${CHR} \
-v y \
-c 2 \
-t exon_skip \
--labelA=HIV \
--labelB=Ctrl \
> ./output_${CHR}/spladder_test.log 2>&1

Loading expression counts from ./output_Y/spladder/genes_graph_conf2.merge_graphs.gene_exp.hdf5
Estimating size factors
Testing exon_skip events
Collecting intron confirmation values
Traceback (most recent call last):
  File "/home/rschulz/bin/spladder/python//spladder_test.py", line 873, in <module>
    main()
  File "/home/rschulz/bin/spladder/python//spladder_test.py", line 787, in main
    (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
  File "/home/rschulz/bin/spladder/python/modules/alt_splice/quantify.py", line 508, in quantify_from_counted_events
    cov[0] += IN['event_counts'][strain_idx, f[0], :][:, event_idx].T
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
  File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 462, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.py", line 88, in select
    sel[args]
  File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.py", line 357, in __getitem__
    raise TypeError("Indexing elements must be in increasing order")
TypeError: Indexing elements must be in increasing order
```
However, comparing Control1, Control2 with HIV1, HIV2, HIV3 (see below) works fine, presumably because the sample order corresponds to the order that was used when spladder.py was called (see above):
```
SPLADDER_HOME=/home/rschulz/bin/spladder/python/
CHR=Y

python $SPLADDER_HOME/spladder_test.py \
-b HIV1.$CHR,HIV2.$CHR,HIV3.$CHR \
-a Control1.$CHR,Control2.$CHR \
-n 101 \
-o ./output_${CHR} \
-v y \
-c 2 \
-t exon_skip \
--labelB=HIV \
--labelA=Ctrl \
> ./output_${CHR}/spladder_test.log 2>&1

Loading expression counts from ./output_Y/spladder/genes_graph_conf2.merge_graphs.gene_exp.hdf5
Estimating size factors
Testing exon_skip events
Collecting intron confirmation values
Constructing event IDs
Estimating size factors
Exclude 19 of 116 exon_skip events (16.38 percent) from testing due to low coverage
Consider 182 unique event splice forms for testing
Estimating raw dispersions
...
Writing test results to ./output_Y/testing_Ctrl_vs_HIV/test_results_C2_exon_skip.tsv
```

**Comment by akahles** [comment]
Thank you for reporting. I pushed a fix for this issue to the development branch. Please re-open if still persistent.

**Comment by carina-paola** [comment]
> To illustrate, below spladder.py is called with the sample order Control1, Control2, HIV1, HIV2, HIV3:
> 
> ```
> SPLADDER_HOME=/home/rschulz/bin/spladder-1.0.0/python/
> CHR=Y
> 
> mkdir -p ./output_${CHR}
> 
> python $SPLADDER_HOME/spladder.py \
> -a ./input/gencode.v24.annotation.$CHR.gff3 \
> -b ./input/bam/Control1.$CHR.bam,./input/bam/Control2.$CHR.bam,./input/bam/HIV1.$CHR.bam,./input/bam/HIV2.$CHR.bam,./input/bam/HIV3.$CHR.bam \
> -n 101 \
> -o ./output_${CHR} \
> -v y \
> -c 2 \
> -M merge_graphs \
> -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip \
> > ./output_${CHR}/spladder.log 2>&1
> ```
> If spladder_test.py is called to compare HIV1, HIV2, HIV3 with Control1, Control2, the result is an index error:
> 
> ```
> SPLADDER_HOME=/home/rschulz/bin/spladder/python/
> CHR=Y
> 
> python $SPLADDER_HOME/spladder_test.py \
> -a HIV1.$CHR,HIV2.$CHR,HIV3.$CHR \
> -b Control1.$CHR,Control2.$CHR \
> -n 101 \
> -o ./output_${CHR} \
> -v y \
> -c 2 \
> -t exon_skip \
> --labelA=HIV \
> --labelB=Ctrl \
> > ./output_${CHR}/spladder_test.log 2>&1
> 
> Loading expression counts from ./output_Y/spladder/genes_graph_conf2.merge_graphs.gene_exp.hdf5
> Estimating size factors
> Testing exon_skip events
> Collecting intron confirmation values
> Traceback (most recent call last):
>   File "/home/rschulz/bin/spladder/python//spladder_test.py", line 873, in <module>
>     main()
>   File "/home/rschulz/bin/spladder/python//spladder_test.py", line 787, in main
>     (cov, gene_idx, event_idx, event_ids, event_strains) = quantify.quantify_from_counted_events(CFG['fname_events'], sp.r_[idx1, idx2], event_type, CFG)
>   File "/home/rschulz/bin/spladder/python/modules/alt_splice/quantify.py", line 508, in quantify_from_counted_events
>     cov[0] += IN['event_counts'][strain_idx, f[0], :][:, event_idx].T
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2582)
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir-------/h5py/_objects.c:2541)
>   File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 462, in __getitem__
>     selection = sel.select(self.shape, args, dsid=self.id)
>   File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.py", line 88, in select
>     sel[args]
>   File "/home/rschulz/anaconda/lib/python2.7/site-packages/h5py/_hl/selections.py", line 357, in __getitem__
>     raise TypeError("Indexing elements must be in increasing order")
> TypeError: Indexing elements must be in increasing order
> ```
> However, comparing Control1, Control2 with HIV1, HIV2, HIV3 (see below) works fine, presumably because the sample order corresponds to the order that was used when spladder.py was called (see above):
> 
> ```
> SPLADDER_HOME=/home/rschulz/bin/spladder/python/
> CHR=Y
> 
> python $SPLADDER_HOME/spladder_test.py \
> -b HIV1.$CHR,HIV2.$CHR,HIV3.$CHR \
> -a Control1.$CHR,Control2.$CHR \
> -n 101 \
> -o ./output_${CHR} \
> -v y \
> -c 2 \
> -t exon_skip \
> --labelB=HIV \
> --labelA=Ctrl \
> > ./output_${CHR}/spladder_test.log 2>&1
> 
> Loading expression counts from ./output_Y/spladder/genes_graph_conf2.merge_graphs.gene_exp.hdf5
> Estimating size factors
> Testing exon_skip events
> Collecting intron confirmation values
> Constructing event IDs
> Estimating size factors
> Exclude 19 of 116 exon_skip events (16.38 percent) from testing due to low coverage
> Consider 182 unique event splice forms for testing
> Estimating raw dispersions
> ...
> Writing test results to ./output_Y/testing_Ctrl_vs_HIV/test_results_C2_exon_skip.tsv
> ```

Dear Andre, could you please tell me what the parameters -n, -v and -M mean? I am looking for that information in the tutorial but I don't find it. And I don't have any .log file in my results, is that bad?

Many thanks,

Paola

**Comment by akahles** [comment]
Dear Paola,
If you run SplAdder without parameters, you should get an overview of the different parameters. In older versions this did not always work correctly, but this should have been fixed in the latest versions. I would also recommend to switch to the latest release of SplAdder.

Answering your specific questions:
`-n` is the read length of your reads
`-v` switches on verbose output
`-M` is the mode in which spladder runs on multiple files (in the example above the mode is `merge_graphs` which would build one graph per gene per input file and will then for each gene merge  the graphs across all input files)
