### ISSUE TITLE
partial intron retention

### ISSUE THREAD

**Issue by pegahsafa** [ratschlab/spladder#37]
Hi there,

I am interested in possibly modifying spladder's cutoffs/parameters to enable detection of partial intron retention, particularly in genes with very big introns. For example, I have some known AS events in cell line data where a transcript is truncated, ending between two exons, where the intron between them is partially retained, and I noticed that spladder does not identify these.

One criterion I noticed that is likely causing this is the minimum fraction of covered positions in the intron being 0.75-0.9. Do you have any suggestions on how I could possibly achieve detection of events like the one described above? Any help would be appreciated.

P.S. Many thanks for developing/maintaining spladder :)

Best,
Pegah

**Comment by akahles** [comment]
Hi Pegah,

Thank you for using SplAdder. From what you describe I understand that you are looking for alternative transcript ends in your data. Currently, SplAdder only focuses on events within the transcript and does not identify alternative ends. The only thing that SplAdder could do is to detect the full intron as retained (not picking up the correct end). If you would like to try that out, you can do the following. In the file `modules/settings.py` look for the following block (depending on the confidence level you are using):
```
...
CFG['intron_retention']['min_retention_cov'] = 10 
CFG['intron_retention']['min_retention_region'] = 0.9  
CFG['intron_retention']['min_retention_rel_cov'] = 0.2                                                                                                                                                                                                                                                            
CFG['intron_retention']['max_retention_rel_cov'] = 1.2 
CFG['intron_retention']['min_retention_max_exon_fold_diff'] = 4 
...
```
Then adapt `min_retention_region` down to something like 0.3 and `min_retention_cov` to 1 or 0. You can also play around a bit and see what you get. However, this will also introduce a lot of noise and you will see a lot of junk coming up. But it might be worth a try.

Cheers,
Andre

PS: I will close this for now (as it is not bug per se), but feel free to comment back and I'll reply.

**Comment by pegahsafa** [comment]
Hi Andre,

Thanks for your reply. I will give that a try.

Even if spladder doesn't identify that it is a terminal exon, that would still be very useful.

If I have a novel exon that falls within an intron (no shared junctions with adjacent exons), I'm assuming that this type of event would fall under the category of a novel cassette exon (as described in your publication). I have set the --insert_es flag to yes, but am wondering to which output file the info about these exons is written?
