### ISSUE TITLE
ploting error : ValueError: too many values to unpack

### ISSUE THREAD

**Issue by jiahsinhuang** [ratschlab/spladder#38]
Hi Andre, I have tried to do the visualisation for my results but I got the error as below. Do you have any idea what the problem was?  

$ python ../GitHub/spladder/python/spladder_viz.py -o spladder_AS/spladder_srr23_test/  -b HISAT2_Stringtie_Ballgown/sorted.bam/SRR1055723.hisat2.sorted.bam  -g gene:FBgn0032938 -c 3 -T -e exon_skip_186
Traceback (most recent call last):
  File "../GitHub/spladder/python/spladder_viz.py", line 251, in <module>
    spladder_viz()
  File "../GitHub/spladder/python/spladder_viz.py", line 179, in spladder_viz
    plot_event(options, event_info, axes[-1], xlim)
  File "../GitHub/spladder/python/spladder_viz.py", line 245, in plot_event
    event_list = [_ for event in load_events(options, event_info) for _ in [event.exons1, event.exons2]]
  File "/Users/jhhuang/IIS_jhh/GitHub/spladder/python/modules/identity.py", line 41, in load_events
    (events, _) = cPickle.load(open(os.path.join(options.outdir, 'merge_graphs_%s_C%s.pickle' % (event_type, options.confidence)),'r'))
ValueError: too many values to unpack

## my target gene output
2L	+	exon_skip_186	gene:FBgn0032938	21275724	21275806	21277278	21278429	21281132	21281337	20.0	8.8	17.4	7	16	14	0.45

**Comment by dnrichardson** [comment]
Hi jiahsinhuang,

I just had this problem and was able to work around it this morning. After manually loading a "merge_graphs" pickle file in an interactive python session using the cPickle.load function, I saw that the resulting array only had a single dimension. 

The code at line 41 of identity.py: 

`(events, _) = cPickle.load(open(os.path.join(options.outdir, 'merge_graphs%s_C%s.pickle' % (event_type, options.confidence)),'r'))`  

expects to unpack two values when there's really only one. 

Changing the offending line to the below should solve your problem. At least, it worked for me! 

`events = cPickle.load(open(os.path.join(options.outdir, 'merge_graphs%s_C%s.pickle' % (event_type, options.confidence)),'r'))`

**Comment by akahles** [comment]
Thanks, I had fixed that earlier but somehow it got lost again. Just pushed the fix again to the development branch.
