### ISSUE TITLE
Overlapping Genes

### ISSUE THREAD

**Issue by rikaiese** [ratschlab/spladder#39]
Hi,
first I would like to thank you for developing this tool, it is really promising!
I am trying to use Spladder on a Mus musculus RNA-seq dataset and I have a question regarding the initial processing of the GFF3/GTF files. I understand that overlapping genes and genes sharing exons are removed from the analysis. In the current mouse annotation there are about 47000 genes, however only about 27000 are left after Spladder filtering. If it is possible could you please explain why those genes are removed and, secondly, is there anyway to make Spladder process those genes as well? I am afraid there is a big loss of information right now.
Thank you for your time
Riccardo

**Comment by akahles** [comment]
Hi Riccardo,
Thank you for using SplAdder. I am aware of the overly conservative filtering and am working on a better solution. If you want to switch off filtering for now, you can do this by changing the line ```CFG['filter_overlapping_genes'] = True``` in modules/settings.py into ```CFG['filter_overlapping_genes'] = False```.
Cheers,
Andre

**Comment by khericlim** [comment]
Hi Andre, do you mind explaining exactly how the overlapping filtering works? Thanks.

**Comment by DarioS** [comment]
Any two genes that have any overlap, even by a single exon, are discarded from the analysis. It'd a terrible methodology decision, especially if the RNA-seq data is strand-specific and there's really no problem regarding overlapping genes.

**Comment by akahles** [comment]
This strategy has been revised and the stringent filtering on gene level is no longer done. Instead, for any intron taken from RNA-Seq data the strand is now correctly recognized and only introns are ignored that overlap to multiple gene loci on the same strand.
