### ISSUE TITLE
ValueError: invalid type: int64

### ISSUE THREAD

**Issue by wuqijia** [ratschlab/spladder#40]
Hi Andre,

I am running spladder with RNA-seq data of silkworms, the gff of which was downloaded from NCBI. After several tries of re-formatting the .gff file, I loaded the gff successfully, and the script goes well in the **intron loading**  step and **casette exons insertion** step. However it dies at the **intron retentions insertion** step, with the following message:

`Inserting intron retentions ...`
`^M 100(11654) genes done (found 0 new retentions in 369 tested introns, 0.0%)
Traceback (most recent call last):`
`File "/home/lzc/soft/spladder-master/python/spladder.py", line 322, in <module> spladder()`
`File "/home/lzc/soft/spladder-master/python/spladder.py", line 223, in splatter spladder_core(CFG)`
`File "/home/lzc/soft/spladder-master/python/modules/core/spladdercore.py", line 21, in spladder_core genes = gen_graphs(genes, CFG)`
`File "/home/lzc/soft/spladder-master/python/modules/core/gen_graphs.py", line 113, in gen_graphs genes, inserted_ = insert_intron_retentions(genes, CFG)`
`File "/home/lzc/soft/spladder-master/python/modules/editgraph.py", line 367, in insert_intron_retentions new_retention = scipy.sparse.linalg.expm(new_retention)`
`File "/usr/lib64/python2.7/site-packages/scipy/sparse/linalg/matfuncs.py", line 113, in expmraise` `ValueError("invalid type: "+str(A.dtype))`
`ValueError: invalid type: int64`
`(END)`

Here is my command:
`python /home/lzc/soft/spladder-master/python/spladder.py -b ../mapping/bam/BmNPV-1.sorted.bam,../mapping/bam/BmNPV-2.sorted.bam,../mapping/bam/BmNPV-4.sorted.bam,../mapping/bam/WT-1.sorted.bam,../mapping/bam/WT-3.sorted.bam,../mapping/bam/WT-4.sorted.bam -R 1,1,1,2,2,2 -a /home/lzc/silkworm/genome/my.gff -o ../AS -v y --output_struc=y`

Can you figure out the causes of this problem ?
Thanks,

WQJ

**Comment by wuqijia** [comment]
update 2016.8.14:

After examining the source code of the mentioned scripts in the Error message, I found in script "edit graph.py", variable "new_retention" was declared as "int", which will return  Error in the "expm" function in matfuncs.py. So I modified "editgraph.py" myself, changed the corresponding "int"s to "float"s, i.e., 
from
>#320 new_retention = sp.zeros(gg.splicegraph.edges.shape, dtype='int') 

to

>#320 new_retention = sp.zeros(gg.splicegraph.edges.shape, dtype='float') 

the program passes the "intron retentions insertion" step, and by far I didn't get error message.

But still I don't know whether the changes I made  will do any harm to the results or not, because I am not familar with programming. So I still need your help.

WQJ

**Comment by akahles** [comment]
Hi WQJ,

Which scipy version are you currently using? It should not be necessary to change the type.

Cheers,
Andre

**Comment by wuqijia** [comment]
Hi Andre，

Thanks for your quick reply, my scipy version should be "scipy-0.12.1“，thanks for your help~~


WQJ

**Comment by akahles** [comment]
I did some further search and it seems that the `expm` function in scipy-0.12* has some type checking built in. Later versions are more general. I will need to raise my requirements to scipy-0.13.0 and above. I would recommend that you upgrade to a more recent Scipy version.
Thanks for reporting this issue!

Cheers,
Andre

**Comment by wuqijia** [comment]
Hi andre,

As I mentioned in the last email by changing A.dtype from int to float, I passes the intron retention insertion step and the program goes to the next step. However I encountered another ERROR shortly after that: the program reports that  variable “r_idx” is not defined in the analyze.py（sorry I didn’t save that error message so I can’t show you this time). Is this a consequence if my change of the type of “A.dtype”? 

And by examing your code in analyze.py, I do find that r_idx is not declared or assigned a value. 


One more question:

how to use the option " -F FILE"? what is exactly the output file, the pickle files? all of them or just a specific one? I've tried and failed several times, please help me with this because it takes too long to run the program from the very beginning. 

Thanks~~

WQJ

**Comment by akahles** [comment]
I am about to deprecate `r_idx`. It will be gone in the next version. Please don't use it. It is only relevant for the testing part and there you choose replicates differently. The detection and counting does not need the replicate information.

The option -F is a relic of the old Matlab version and never really needed in normal use. It was created to rescue SplAdder runs that were started and broke of to various issues. I will put it onto my deprecation list as well.

Cheers,
Andre

**Comment by wuqijia** [comment]
Hi Andre, 

Thanks for your reply. I run the program again without the "-R" option, and get the correct results with no error reported. Thanks again Andre, it's a nice program and I really love it: the presentations of the results are very straight forward and easy to be read, and the plots are beautiful. 

However I can’t get the same splicing graph as generated using the example data. The example figure includes reads coverage of two groups, plus a combined coverage illustration. The figure I generated has no group information (only 1 group), and the “Alt event structure” was not plotted, as shown in the figure attached. 

The command I used is similar to that in the example_run.sh, which has no group definition. Would you pls help me to generate the same figure as in the example? Thanks!!

Command in example_run.sh:
<python spladder.py -b $bams -o $outdir -a $anno -v y -M merge_graphs -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -c 3 -p n>

my command:
<python /home/lzc/soft/spladder-master/python/spladder.py -b ../mapping/bam/BmNPV-1.sorted.bam,../mapping/bam/BmNPV-2.sorted.bam,../mapping/bam/BmNPV-4.sorted.bam,../mapping/bam/WT-1.sorted.bam,../mapping/bam/WT-3.sorted.bam,../mapping/bam/WT-4.sorted.bam -a /home/lzc/silkworm/genome/my.gff -o ../AS -v y --output_struc=y>

Best wishes,

WQJ

**Comment by wuqijia** [comment]
by the way, how can I know which sample the colours in the attached figure stand for?

**Comment by akahles** [comment]
Please re-open if still relevant.
