### ISSUE TITLE
parallel jobs with mpi

### ISSUE THREAD

**Issue by misik** [ratschlab/spladder#41]
Hello,

When I use the options -p y --parallel 25, I get the following error:
Could you please solve this issue?

Traceback (most recent call last):
  File "spladder-master/python/spladder.py", line 322, in <module>
    spladder()
  File "spladder-master/python/spladder.py", line 221, in spladder
    jobinfo.append(rp.rproc('spladder_core', CFG, 15000, CFG['options_rproc'], 60*60))
  File "/n/data2/joslin/icrb/blackwell/mi51/SUPPA/rMATS/rMATS.3.2.4/WTvsraga1/spladder-master/python/modules/rproc.py", line 241, in rproc
    os.symlink(sge_tmp_dir, os.path.join(os.environ['HOME'], 'tmp', '.sge'))
NameError: global name 'sge_tmp_dir' is not defined

**Comment by akahles** [comment]
Hi, Thank you for trying out SplAdder. The software has two different ways of parallelizing. The first one is via --parallel <n> which will use multiple threads on the same machine to parallelize some computations. The second one is with the switch -p y/n, which will spawn off jobs to a compute cluster using a scheduler such as SGE, torque or LSF. The latter ist still somewhat experimental and needs some setup (which is the main reason for it to be listed under the experimental section of the parameters). I would suggest, you use ```-p n --parallel 25``` for now (unless you really want to process hundreds of bam files and distribute over a cluster. Let me know, then I write a more detailed explanation on how to set it up. (You might need to do some tweaking, to get it to work in your specific HPC environment.)

Cheers,
Andre

**Comment by misik** [comment]
Hello Andre,

I've a lot of files and I'd like to distribute the job over the cluster.
Could you please write me how to use the -p y option? I am using LSF (
https://wiki.med.harvard.edu/Orchestra/WebHome).

Thank you,

Meltem

**Comment by motomurad** [comment]
Hello,
I also want to handle hundreds of bams. I want to parallelize and process each bam on UGE <https://supcom.hgc.jp/english/utili_info/manual/uge.html#2694>, but I could not find that way on wiki. Could you tell me how to solve it?

**Comment by Nitin123-4** [comment]
I am 
--parallel 25 option is not taking threads and the process is taking long time to run. Is there any way we can fix it?
