### ISSUE TITLE
ValueError: Zero sided dimension

### ISSUE THREAD

**Issue by MatteoSchiavinato** [ratschlab/spladder#44]
Hi, 
In my group we are running Spladder and we ended up in some problems. We made a sample of 1 gene from the GFF3 reference file, and tried to run it. It runs fine until it reaches the point where:

`counting 1 genes on contig 0010.scaffold00043`
`.Traceback (most recent call last):`
`File "/software/spladder/spladder/python/spladder.py", line 322, in <module>`
`spladder()`
`File "/software/spladder/spladder/python/spladder.py", line 302, in spladder`
`count_graph_coverage_wrapper(fn_in_count, fn_out_count, CFG)`
`File "/software/spladder/spladder/python/modules/count.py", line 156, in count_graph_coverage_wrapper`
`h5fid.create_dataset(name=key, data=counts[key])`
`File "/software/python/Python2.7/lib/python2.7/site-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/group.py", line 103, in create_dataset`
`dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)`
`File "/software/python/Python2.7/lib/python2.7/site-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/dataset.py", line 120, in make_new_dset`
`sid = h5s.create_simple(shape, maxshape)`
`File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/software/python/Python2.7/lib/python2.7/site-packages/h5py-2.5.0/h5py/_objects.c:2574)`
`File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/software/python/Python2.7/lib/python2.7/site-packages/h5py-2.5.0/h5py/_objects.c:2533)`
`File "h5py/h5s.pyx", line 99, in h5py.h5s.create_simple (/software/python/Python2.7/lib/python2.7/site-packages/h5py-2.5.0/h5py/h5s.c:1432)`
`ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)`

I attached the subset reference that arises the error (the BAM file is ok). 

[subset.gff3.zip](https://github.com/ratschlab/spladder/files/474092/subset.gff3.zip)

**Comment by akahles** [comment]
There subset.gff3 seems to have an incorrect format. Please re-open if still relevant.
