### ISSUE TITLE
IndexError in spladder_test

### ISSUE THREAD

**Issue by heseber** [ratschlab/spladder#50]
## Error message

I get an IndexError in spladder_test.py (using the development branch because of #35):

```
Traceback (most recent call last):
  File "spladder/python/spladder_test.py", line 985, in <module>
    main()
  File "spladder/python/spladder_test.py", line 900, in main
    (pvals, cov_used, disp_raw_used, disp_adj_used) = run_testing(cov, dmatrix0, dmatrix1, sf, CFG, event_type)
  File "spladder/python/spladder_test.py", line 636, in run_testing
    (disp_fitted, Lambda, disp_idx) = fit_dispersion(cov, disp_raw, disp_raw_conv, sf, CFG, dmatrix1, event_type)
  File "spladder/python/spladder_test.py", line 347, in fit_dispersion
    lowerBound = sp.percentile(sp.unique(disp_raw[index]), 1)
  File "<MYHOME>/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3699, in percentile
    interpolation=interpolation)
  File "<MYHOME>/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3425, in _ureduce
    r = func(a, **kwargs)
  File "<MYHOME>/anaconda2/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3816, in _percentile
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "<MYHOME>/anaconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 124, in take
    return take(indices, axis, out, mode)
IndexError: cannot do a non-empty take from an empty axes.
```

## How I ran spladder

This is the command I used for running spladder :

```
    python $spladderScript \
        -b $bamlinks \
        -a $GTF \
        -o $OUTDIR \
        -v y \
        -c 3 \
        -M merge_graphs \
        -T y \
        -V n \
        -n 125 \
        -P y \
        -p n \
        -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip
```

where `$GTF` is gencode.v25.primary_assembly.annotation.gtf filtered for protein coding genes, and `$bamlinks` is a comma separated list of 25 BAM files. Some warnings were produced:

```
spladder/python/modules/editgraph.py:923: RuntimeWarning: divide by zero encountered in double_scalars
  (sp.median(exon_cov[-min_len_aft:]) / sp.median(aft_segment_cov[:min_len_aft])) - 1 >= CFG['cassette_exon']['min_cassette_rel_diff'] and \
spladder/python/modules/editgraph.py:924: RuntimeWarning: divide by zero encountered in double_scalars
  (sp.median(exon_cov[:min_len_pre]) / sp.median(pre_segment_cov[-min_len_pre:])) - 1 >= CFG['cassette_exon']['min_cassette_rel_diff']:
```

## How I ran spladder_test

This is the command I used for running spladder_test (names of samples and labels were anonymized here):

```
    python $SPLADDER_TEST \
    --outdir=$OUTDIR \
    --conditionA=sample04,sample12,sample15,sample1a,sample25,sample9a \
    --conditionB=sample22,sample23,sample24 \
    --labelA=group1 \
    --labelB=group2 \
    --readlen=125 \
    --confidence=3 \
    --event_types=exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons \
    --merge_strat=merge_graphs \
    --validate=n \
    --matlab=n \
    --subset_samples=n \
    --correction=BH \
    --max_zero_frac=0.5 \
    --min_count=10 \
    --verbose=y \
    --debug=n \
    --diagnose_plots=n \
    --timestamp=n
```
Do you have any ideas why spladder_test fails?

**Comment by heseber** [comment]
I would like to add that `$bamfiles` contains the full path specification for each BAM file, and in spladder_test I used the basename of the BAM files (without extension .bam) in conditionA and conditionB. I also tried adding ".bam" to the basename, which did not work either. Would I have to specify the full path name in spladder_test as well? How is the matching of BAM file names from spladder to the conditionA and conditionB specification done? Full path, full path without extension ".bam", basename only, or any of them?

**Comment by akahles** [comment]
The matching of the list input files is exactly as you described. To derive a sample ID, the basename of the given file is trimmed, removing  the `.bam` extension. I fixed a small inconsistency between the extension matching for spladder.py and spladder_test.py that I just pushed to development. I also pushed quite some more changes regarding the testing. Would you mind giving it another try and let me know whether your problem still persists?

My apologies, that the reply took a while and thank you for your patience.

Cheers,
Andre

**Comment by heseber** [comment]
Dear André,

last week I found some time for testing whether your latest modifications solved this issue (development branch, 21486a31d3aea8dcbcddf440cc8de73eb5f0eb2e). I am sorry to say that it did not. The error message from spladder_test is "IndexError: cannot do a non-empty take from an empty axes.". I attach a zip file with the command lines and the stdout and stderr of spladder and spladder_test. Please let me know if there is anything I can do to help tracking down the cause of this issue. Thanks!

Just for completeness, this is the command I used for mapping:
```
STAR \
  --runThreadN $THREADS \
  --genomeDir $STARINDEX \
  --readFilesIn $file1 $file2 \
  --outFileNamePrefix $outdir/$outprefix/ \
  --quantMode TranscriptomeSAM \
  --outMultimapperOrder Random \
  --outFilterType BySJout \
  --outFilterMultimapNmax 20 \
  --outSAMattributes NH HI AS NM nM MD \
  --outSAMunmapped Within \
  --readFilesCommand zcat
```
The STAR index I used is for GRCh38_gencode25 (both the genome FASTA files and the gencode GTF file were dowloaded from gencode). Afterwards I used samtools to convert SAM to BAM and to sort the BAM files. 

Best regards
Henrik
[spladder_logs.zip](https://github.com/ratschlab/spladder/files/823733/spladder_logs.zip)

**Comment by akahles** [comment]
Hi Henrik,
Thank you very much for re-running. I have added a check to the development branch. I have a suspicion, that the dispersion estimates are not converging for your data (although I do not know yet why). Would you mind running the test again with the current code? I have added a check that lets the program exit in case the estimates indeed do not converge.

Thanks and Cheers,
Andre

**Comment by heseber** [comment]
Dear André,

that's true:

ERROR: None of the dispersion estimates converged. Exiting.

Okay, how to proceed from here?

Best regards
HEnrik

**Comment by akahles** [comment]
Please re-open if still relevant.
