### ISSUE TITLE
Improve Tutorial Explanations

### ISSUE THREAD

**Issue by DarioS** [ratschlab/spladder#51]
For example, instead of simply showing the reader that `-b examples/NMD_WT1.tiny.bam,examples/NMD_WT2.tiny.bam,examples/NMD_DBL1.tiny.bam,examples/NMD_DBL2.tiny.bam` is suitable, there should be some explanation of how the software determines which samples belong to which experimental condition and in which direction the differences are calculated in (e.g. DBL - WT or WT -DBL),

It would also be nice if the last page of the tutorial showed the first few lines of the confirmed text file and explain why C3 suddenly appeared in all of the file names. Showing the head of result summary file would enable the reader to quickly gauge if the software is what they want or not.

**Comment by akahles** [comment]
I am in the process of replacing the wiki/tutorial with a more general documentation. The current version is available here now: https://spladder.readthedocs.io/
