### ISSUE TITLE
Loading Introns Terminates With Obscure Error

### ISSUE THREAD

**Issue by DarioS** [ratschlab/spladder#54]
It's unclear why the software terminates:

    Loading introns from file ...
    Traceback (most recent call last):
        ...             ...
    File "/verona/nobackup/biostat/software/Python/lib/python2.7/site-packages/modules/reads.py", line 472, in filter_read
    return filter['mismatch'] < tags['NM']
    KeyError: 'NM'

I used GENCODE Genes Human version 25 GFF3 file as the annotation.

**Comment by akahles** [comment]
Thanks for reporting. This happens, when the input BAM file does not have the 'NM' tag present. A more meaningful error message is already provided in the development branch of the code and will in make it into master with the next version.

**Comment by DarioS** [comment]
The SAM format specification explains that NM is an optional tag and Spladder's documentation does not state that the reads must have NM values recorded. Why is it necessary? Could the limitation be removed? By default, STAR doesn't output these, but can if the option `--outSAMattributes NM` is specified. If this requirement of Spladder was documented, I wouldn't need to map all of the samples again.

**Comment by akahles** [comment]
I will add the requirement to the README to make it more evident. Meanwhile, the development branch has an option `--ignore_mismatches` that will ignore the NM tag requirement. The edit operations are internally used for filtering the input alignments. Ignoring the NM tag will just take all the reads then. Another possible option would be that I add the nM as optional filter tag. This is part of the tags output in the default STAR settings and denotes the edit operations per fragment. It should be ok to use as a proxy and would not require for you to remap your reads.

SplAdder is updated, maintained and improved on a best efforts basis. Your patience is appreciated.

**Comment by DarioS** [comment]
`--ignore_mismatches` suits me. Only the high confidence reads are in the resulting BAM file and I'm happy to use them all.

Thanks for updating SplAdder after the journal publication!
