### ISSUE TITLE
SplAdder handling of reads spanning multiple junctions

### ISSUE THREAD

**Issue by ajw2329** [ratschlab/spladder#55]
Dear Dr. Kahles,

Thanks again for writing such a great tool!

As I work with longer reads, I'm seeing a lot that span multiple splice junctions.  It looks as though SplAdder may be considering junctions only individually - is this the case?  Specifically I'm seeing scenarios where a read contains one junction that's consistent with an event, and a second that is inconsistent with the event, but the read is still counted as contributing to the event.  E.g. a single exon skip overlaps with a multiple exon skip (same flanking exons for both events) - reads containing all 3 junctions of the single exon skip should not be counted towards the multiple exon skip, but still appear to be.

Also, if a single read contains two junctions consistent with an event, is it then counted twice for that event?

Thanks again!
Best,
Andrew

**Comment by akahles** [comment]
All quantifications are made independently for each event. Hence, if an intron is shared by multiple events, reads are counted multiple times (once towards the expression of each event). 

Multiple introns per gene should not be problematic, as long as the aligner supports to align them. All intron counts are extracted from the Cigar string in the BM files.

**Comment by ajw2329** [comment]
Thanks very much for getting back to me.

The question is really about reads that span multiple splice junctions, and whether the presence of certain junctions in combination can ever disqualify a read from contributing to a specific event's junction count.

For example, say there is a skipped exon (SE) event whose included form introns have the following coordinates: (500, 1500) and (1575, 5000)

Now imagine you have a read that spans 2 introns with the following coordinates:  (500,1500) and (1600, 3000).

The first splice junction in the read is consistent with the first SE event included form intron and could conceivably be counted toward the read count for this junction in this event isoform.  However, the second splice junction in the read is inconsistent with the possibility that the read was derived from a transcript corresponding to the event at all.  So my question is the following:  will this read contribute to the junction read count for this event?

Thanks again.

**Comment by akahles** [comment]
Hi @ajw2329,

SplAdder will only take into account "local" information and thus would count each intron independently (even when longer reads would support pairs). However, I get your point and see the value in using the dependency between introns in long reads for a more accurate event detection and quantification. I will add it to my list of future improvements to allow for long-read filtering of events.

Cheers,

Andre
