### ISSUE TITLE
visualizing spladder ouput

### ISSUE THREAD

**Issue by dkriti** [ratschlab/spladder#58]
Hello!

I was trying to use spladder on my data but I cannot figure out to visualize the spladder output. The 'Result Inspection Phase' link in the wiki does not work. can I get some help for this?

Thanks!

**Comment by DrJCampbell** [comment]
I would also like to know how to generate the visualisations shown in the wiki examples. Thanks

**Comment by akahles** [comment]
I have rewritten the visualisation part of SplAdder for the latest release. Please refer to the online documentation (https://spladder.readthedocs.io/en/latest/) for further information. Please open a new issue in case further arise.
