### ISSUE TITLE
Spladder issue in init_genes_gff3     gene_id = trans2gene[trans_id]

### ISSUE THREAD

**Issue by niccole96** [ratschlab/spladder#59]
I'm new in working with alternative splicing, and i wrote this script to run spladder 
so the example data from the programs runs just fine but when i try my bam files and genome( bos taurus  gff3 genome from ensemble i get this error : 
t-mr321@bssv-watson:/mnt/data/t-mr321$ sh spladdercows.sh 
spladdercows.sh: 20: [: missing ]
Parsing annotation from ./gff/Bos_taurus.singen.UMD3.1.83.gff3 ...
... init structure
Traceback (most recent call last):
  File "/mnt/data/au207/spladder-master/python/spladder.py", line 322, in <module>
    spladder()
  File "/mnt/data/au207/spladder-master/python/spladder.py", line 144, in spladder
    (genes, CFG) = init.init_genes_gff3(CFG['anno_fname'], CFG, CFG['anno_fname'] + '.pickle')
  File "/mnt/data/au207/spladder-master/python/modules/init.py", line 256, in init_genes_gff3
    gene_id = trans2gene[trans_id]
KeyError: 'transcript:ENSBTAT00000064346'

If i remove the transcript it says and run it again so many more transcripts still appear , but i dont think removing one by one is the solution. Could it be maybe a problem of indexing, should i use picard to index the bam files and then run spladder? 
( bam files are already sorted) 

######
basedir="./bam/malesCows"
gff="./gff"
annotation=${gff}/Bos_taurus.UMD3.1.83.gff3
bams=${basedir}/Cow_Brain_Male_1320sTS-sorted.bam,${basedir}/Cow_Cerebellum_Male_1310sTS-sorted.bam,${basedir}/Cow_Heart_Male_1312sTS-sorted.bam,${basedir}/Cow_Liver_Male_1311sTS-sorted.bam,${basedir}/Cow_Testis_Male_1309sTS-sorted.bam
outdir=${basedir}/results_Cows

##run SplAdder
python /mnt/data/au207/spladder-master/python/spladder.py -b $bams -o $outdir -a $annotation -v y -M merge_graphs -T y -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -c 3 -p n

### run visualization
python /mnt/data/au207/spladder-master/python/spladder_viz.py -o ${basedir}/results_Cows -b $bams -c 3 -T -v -t exon_skip,intron_retention,alt_3prime,alt_5prime,mult_exon_skip,mutex_exons
###

**Comment by akahles** [comment]
Please re-open the issue if still relevant.
