### ISSUE TITLE
Regarding replicate option

### ISSUE THREAD

**Issue by jeffinrockey** [ratschlab/spladder#6]
Hi Andre,
While using   -R R1,R1,R2,R2 for a four sample, two replicates each treatment scenario, the below error showed up.

....../spladder/python/modules/settings.py", line 227, in parse_args
    CFG['replicate_idxs'] = [int(x) for x in options.replicates.split(',')]
ValueError: invalid literal for int() with base 10: 'R1'

From the error trace it looked like integers are expected instead of Rs there.I tried 1,1,2,2 and it seems to work. Present spladder help says

-R R1,R2,..., --replicates=R1,R2,...
                        replicate structure of files (same number as alignment
                        files) [all R1 - no replicated] 

which I suppose should be -R INT 1,2 ...  [all 1 - no replicated]  or so if the present split implementation itself is the expected one for -R usage.

Please do correct me in case I  have understood  the replicate option usage all wrong or so.

Regards,
Jeffin

**Comment by jeffinrockey** [comment]
An update,
 When I gave only ints , the run got affected in a subsequent step...

.../spladder/python/modules/alt_splice/analyze.py", line 50, in analyze_events
    rep_tag = '_R%i' % r_idx
NameError: global name 'r_idx' is not defined

wherein I suppose R prefix itself  is expected.
Hence could you please illustrate the correct option usage for replicates ?
-Jf

**Comment by akahles** [comment]
Hi Jeffin,

Thank you very much for your feedback. The replicate logic is still in a beta-state. I will look into the behavior that you describe and post an update hopefully early next week. 

Cheers,

Andre

**Comment by akahles** [comment]
The replicate options has been removed for the `build` mode of SplAdder.
