### ISSUE TITLE
no “genes_graph_conf3.merge_graphs.gene_exp.hdf5" created

### ISSUE THREAD

**Issue by archanaUEA** [ratschlab/spladder#62]
I got three conditions control, 6hpi, 48hpi (3 replicates each).  I got 50bp single end reads, I did trim-glore to remove adapters, HISAT-2 for alignment, samtools to sort, and index to get the input files.
 
I ran spladder.py (development version) on following parameters:
 
###
python spladder-development/python/spladder.py -v y -T y -c 3 --output_struc y -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -b Col-0_control-rep1_trimmed.sort.bam,Col-0_control-rep2_trimmed.sort.bam,Col-0_control-rep3_trimmed.sort.bam,Col-0_6hpi-rep1_trimmed.sort.bam,Col-0_6hpi-rep2_trimmed.sort.bam,Col-0_6hpi-rep3_trimmed.sort.bam,Col-0_48hpi-rep1_trimmed.sort.bam,Col-0_48hpi-rep2_trimmed.sort.bam,Col-0_48hpi-rep3_trimmed.sort.bam -o spladder -a TAIR10_GFF3_genes.gff -l spladder.log"
 
 
I got output files but when I compare with the test file run provided online I could see the difference that there was no “genes_graph_conf3.merge_graphs.gene_exp.hdf5
“produced for my dataset. 
 
Also foe visulization, when I run spladder_viz.py with following parameter
 
spladder-development/python/spladder_viz.py -o spladder -b Col-0_control-rep1_trimmed.sort.bam,Col-0_control-rep2_trimmed.sort.bam,Col-0_control-rep3_trimmed.sort.bam:Col-0_6hpi-rep1_trimmed.sort.bam,Col-0_6hpi-rep2_trimmed.sort.bam,Col-0_6hpi-rep3_trimmed.sort.bam:Col-0_48hpi-rep1_trimmed.sort.bam,Col-0_48hpi-rep2_trimmed.sort.bam,Col-0_48hpi-rep3_trimmed.sort.bam -L cnt1,6hpi,48hpi -T y -t exon_skip,intron_retention,alt_3prime,alt_5prime,mult_exon_skip,mutex_exons -f png
 
I get following error
 
Traceback (most recent call last):
  File "spladder-development/python/spladder_viz.py", line 297, in <module>
    spladder_viz()
  File "spladder-development/python/spladder_viz.py", line 162, in spladder_viz
    gene.from_sparse()
AttributeError: 'numpy.ndarray' object has no attribute 'from_sparse'

**Comment by akahles** [comment]
This issue should be solved with the latest versions. Please re-open if still relevant.
