### ISSUE TITLE
0 events

### ISSUE THREAD

**Issue by selffi** [ratschlab/spladder#63]
i am trying to find alternative splicing events in my sample. But i am getting the following results:

Loading event data from tutorial/merge_graphs_intron_retention_C3.pickle

No intron_retention event could be found. - Nothing to report
confidence 3 / replicate 0

Loading event data from tutorial/merge_graphs_alt_3prime_C3.pickle

Reporting complete alt_3prime events:

No alt_3prime event could be confirmed. - Nothing to report.
confidence 3 / replicate 0

Loading event data from tutorial/merge_graphs_alt_5prime_C3.pickle

Reporting complete alt_5prime events:

No alt_5prime event could be confirmed. - Nothing to report.
confidence 3 / replicate 0

Loading event data from tutorial/merge_graphs_mult_exon_skip_C3.pickle

No mult_exon_skip event could be found. - Nothing to report

**Comment by akahles** [comment]
This might have been caused by an intermediate state of the code. Should be fixed now. Please re-open if still relevant.

**Comment by wuzhigui** [comment]
![image](https://user-images.githubusercontent.com/70992194/165007417-1809fdee-90d6-465c-bd02-36a8b174a0af.png)
Please !  I  have  the  same  error !!!
Who can help me ?
