### ISSUE TITLE
spladder should not include overlapping annotated exon coverage in intron retention analysis

### ISSUE THREAD

**Issue by benwbooth** [ratschlab/spladder#64]
I am running spladder on a data set and have discovered that when computing the intron retention PSI values, spladder does not exclude the coverage data for overlapping exons included in the input annotation. Is there some way to fix this? I was hoping that by including known cassette exons in the input annotation that those cassette exon reads would not be used to compute the intron retention PSI values. Thanks!

**Comment by akahles** [comment]
I have changed one part of the code now such that introns containing full exons (as in the case for cassette exons) are never added as new retentions to the graph. I will also modify the IR calling to better address your scenario.
