### ISSUE TITLE
Error only when run on cluster, while test well on getway node

### ISSUE THREAD

**Issue by biobai** [ratschlab/spladder#65]
Hi,
I try to run spladder on a cluster like this code
#SBATCH --nodes=1
#SBATCH --ntasks=10
#SBATCH --time=1-10:00:00
#SBATCH --mem=128G
module purge
module restore spladder
anno=...
mappingdir=...
bams=...
outdir=...

rm -rf $outdir
mkdir -p $outdir
spladder.py -b $bams -o $outdir -a $anno -v y -M merge_graphs -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -c 3 -p n --parallel 10 -R 1,1,1,2,2,2

but got the follow error messeges:

python: error: _get_addr: No such file or directory
python: error: _get_addr: No such file or directory
python: error: _get_addr: No such file or directory
Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(784).....: 
MPID_Init(1332)...........: channel initialization failed
MPIDI_CH3_Init(120).......: 
MPID_nem_init_ckpt(852)...: 
MPIDI_CH3I_Seg_commit(307): PMI_Barrier returned -1

While I run this program in gateway node like the same 
spladder.py -b $bams -o $outdir -a $anno -v y -M merge_graphs -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -c 3 -p n --parallel 10 -R 1,1,1,2,2,2
It is well. But the runing time of program is limited not up to 30 mins.
So I need your helps. Thanks in advance

**Comment by akahles** [comment]
Dear biobai,

The error looks like an MPI error. SplAdder does not use message passing and only runs local with parallel threads. So I assume the error stems from your setup/ennvironment.

I will close this issue for now, as I it seems unrelated to the SplAdder codebase. Please re-open if you feel otherwise.

Cheers,
Andre
