### ISSUE TITLE
index error in spladder_test.py

### ISSUE THREAD

**Issue by archanaUEA** [ratschlab/spladder#66]
Hi 

I got 5 replicates in different comparision , data is 150 bp paired end. I ran spladder.py and got pickle files. While running DE I am getting index error.

1. Running spladder.py with following command 

python ./spladder-development/python/spladder.py -v y --parallel=4 -T y -t exon_skip,intron_retention,alt_3prime,alt_5prime,mult_exon_skip -b 7Aligned.out.sort.bam,9Aligned.out.sort.bam,11Aligned.out.bam.sort.bam,17Aligned.out.sort.bam,18Aligned.out.sort.bam,4Aligned.out.sort.bam,5Aligned.out.sort.bam,6Aligned.out.sort.bam,14Aligned.out.sort.bam,15Aligned.out.sort.bam  -o spladder -a Homo_sapiens.Ensembl.GRCh38.82.gtf -l spladder2_trimmed.log.GRCh3

2. Running DE (spladder_test.py) with following command line: 
python ./spladder-development/python/spladder_test.py -o ./spladder -a 7Aligned.out.sort.bam,9Aligned.out.sort.bam,11Aligned.out.bam.sort.bam,17Aligned.out.sort.bam,18Aligned.out.sort.bam -b 4Aligned.out.sort.bam,5Aligned.out.sort.bam,6Aligned.out.sort.bam,14Aligned.out.sort.bam,15Aligned.out.sort.bam  -n 150 -c 3 -D y —-labelA=Old —-labelB=Young -t exon_skip,intron_retention,alt_3prime,alt_5prime,mult_exon_skip -v y

I am getting following error:

Traceback (most recent call last):
  File "./spladder-development/python/spladder_test.py", line 1031, in <module>
    main()
  File "./spladder-development/python/spladder_test.py", line 803, in main
    gene_counts, gene_strains, gene_ids = get_gene_expression(CFG, fn_out=CFG['fname_exp_hdf5'], strain_subset=condition_strains)
  File "./spladder-development/python/spladder_test.py", line 174, in get_gene_expression
    gene_counts[gidx, :] = IN['segments'][seg_idx, :][strain_idx] * seg_lens[seg_idx] / CFG['read_length']
IndexError: index 2 is out of bounds for axis 0 with size 1

Any help would be much appritiated!

Thanks

**Comment by gupta567varun** [comment]
Hi,
was this resolved??

**Comment by archanaUEA** [comment]
No it wasn't resolved unfortunetly . I tried all possible way but then switched to rMATS. However I would really appreciate your help in this regard. I am very much interested to use Spladder. If you like I can send you snapshot of the files that were created after using spladder.py? Please let me know. 

Thanks

**Comment by gupta567varun** [comment]
Hi,
I am also stuck with spladder_test.py script which calculates a significance (p-value) value. But I am having errors running the script. As of now spladder.py does output psi values of the events. I tried a t -test on retained intron events to get a p - value, but t-test said data to be constant. May be just take the psi values and do a ratio between treatment/control to see which introns or events are included more in treatment vs control. We will have to wait for the author to comment on this.

Thanks

**Comment by archanaUEA** [comment]
I see. No problem. In that case please let me know if you could solve the issue. Good luck :)

**Comment by archanaUEA** [comment]
Hi @akahles 

I could run the first python script splatter.py

`

 python ../../../Arabidopsis/LP_Ana/spladder-development/python/spladder.py -v y -T y -c 3 -R 1,1,1,2,2,2,3,3,3 --output_struc y -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -b ../Col-0_control-rep1_trimmed.sort.bam,../Col-0_control-rep2_trimmed.sort.bam,../Col-0_control-rep3_trimmed.sort.bam,../Col-0_6hpi-rep1_trimmed.sort.bam,../Col-0_6hpi-rep2_trimmed.sort.bam,../Col-0_6hpi-rep3_trimmed.sort.bam,../Col-0_48hpi-rep1_trimmed.sort.bam,../Col-0_48hpi-rep2_trimmed.sort.bam,../Col-0_48hpi-rep3_trimmed.sort.bam -o spladder -a ../TAIR10_GFF3_genes.gtf -l spladder.py.log

`

and got the following files

![screen shot 2018-09-14 at 09 33 05](https://user-images.githubusercontent.com/30934642/45539478-cc7ca900-b801-11e8-97cc-5d2a9612308d.png)

2. Reads are 50bp single end and I ran spladder_tesy.py on them with following command

`spladder_test.py -o spladder -a ../Col-0_control-rep1_trimmed.sort.bam,../Col-0_control-rep2_trimmed.sort.bam,../Col-0_control-rep3_trimmed.sort.bam -b ../Col-0_6hpi-rep1_trimmed.sort.bam,../Col-0_6hpi-rep2_trimmed.sort.bam,../Col-0_6hpi-rep3_trimmed.sort.bam -n 50 -c 3 -D y --labelA=control --labelB=6hpi -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -v y`


I an getting following error: 


Quantifying gene expression ...
[                                                                                                    ] 0 / 33432 (0%) - took 0 sec (ETA: 0 sec)Traceback (most recent call last):
  File "../../../Arabidopsis/LP_Ana/spladder-development/python/spladder_test.py", line 1031, in <module>
    main()
  File "../../../Arabidopsis/LP_Ana/spladder-development/python/spladder_test.py", line 803, in main
    gene_counts, gene_strains, gene_ids = get_gene_expression(CFG, fn_out=CFG['fname_exp_hdf5'], strain_subset=condition_strains)
  File "../../../Arabidopsis/LP_Ana/spladder-development/python/spladder_test.py", line 174, in get_gene_expression
    gene_counts[gidx, :] = IN['segments'][seg_idx, :][strain_idx] * seg_lens[seg_idx] / CFG['read_length']
IndexError: index 6 is out of bounds for axis 0 with size 1


Please let me know if you need more information and thanks for the help.
Archana

**Comment by akahles** [comment]
This should be resolved with the latest release of SplAdder. Please re-open if you find otherwise.
