### ISSUE TITLE
Can spladder handle replicates

### ISSUE THREAD

**Issue by gupta567varun** [ratschlab/spladder#68]
Hi,
Can spladder take into account replicates and do a comparison of splicing events in 2 conditions?

**Comment by akahles** [comment]
Hi gupta567varun,

The general strategy is to build a joint splicing graph for all input samples (this is the default) and quantify all edges and nodes independently for each of the samples. Thus, the replicate choice will only become relevant during the differential testing with `spladder_test.py`.

Does that answer your question?

**Comment by gupta567varun** [comment]
Hi,
I understand now that only in the differential testing part spladder_test.py will take replicates into consideration. We get psi values for each event. I tried to do standard t-test on that, but I got an answer from t-test saying data is constant. Kind of puzzled what it means. This is because I was just comparing the psi of control rep1,rep2  with treatment rep1 rep2.

Thanks

**Comment by akahles** [comment]
This might be related to issue #69. Would it be possible for you to share your data in the spladder directory with me?

**Comment by akahles** [comment]
I believe this issue has been addressed, please re-open if still relevant.
