### ISSUE TITLE
On visualization

### ISSUE THREAD

**Issue by jeffinrockey** [ratschlab/spladder#7]
Dear Andre,
   While visualizing the pdf always shows TAIR 10. I suppose the issue is the below line             axes[-1].set_title('Annotated Transcripts (TAIR 10)'). Instead, may be, giving an option to give the Name of the Gene as a user input would be apt.
Also,
Could you please consider providing an option to input actual Sample Names shown in pdf. When the number of samples are more,seeing actual treatment names above the corresponding plot instead of Sample1,2,3  would really be of much help.
Regards,
Jf

**Comment by akahles** [comment]
Hi Jeffin,

Thanks for reporting. I have implemented all the changes already and they will become available very shortly (this week). There are also some other features added which I would like to test before I make the push to master.  Currently, I provide the option to let the user specify labels for the sample groups.

Best,

Andre

**Comment by akahles** [comment]
Sorry that this took so long - got busy with other projects. I have pushed the changes to the visualization code and will hopefully be adding new features over the next weeks.

**Comment by jeffinrockey** [comment]
Thanks Andre.
