### ISSUE TITLE
Nonstop running

### ISSUE THREAD

**Issue by jiwoongbio** [ratschlab/spladder#70]
Hello,

I mapped RNA-seq reads to hg38 genome using STAR and sorted them using samtools, and then executed the following spladder command:

python spladder-1.1.0/python/spladder.py -b sample.STAR.sorted.bam -o sample.spladder -a igenome/Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf --ignore_mismatches=y

The job looks permanently running. Is there anything wrong in my use?
Thanks.

Best Regards,
Jiwoong

**Comment by akahles** [comment]
Please re-open the issue, if it is still occurring with the latest version of SplAdder. Depending on size and complexity of the input data, a single run can take several hours (up to days if many input files are involved). Using the verbose output (`-v`) helps to identify the current state of the program.

**Comment by jfass** [comment]
I've been seeing this with the most recent spladder; 8 bam files (4 of them ~3GB each; 4 of them ~12GB each). Total cpu time is ~11 days so far, ran it --parallel 16 but I've only ever seen it using one thread.
