### ISSUE TITLE
Spladder for multiple samples

### ISSUE THREAD

**Issue by vjbaskar** [ratschlab/spladder#72]
Is there a tutorial on how to run large number of samples? I have ~150 RNA-seq samples. Thanks!

I see the following in the wiki but the link is not working.
"SplAdder has several possibilities how to integrate input files. However, this would lead to far for this introductory tutorial and we refer to a later tutorial for working with multiple samples."

**Comment by akahles** [comment]
Dear vjbaskar,
I am currently porting SplAdder to Python3, also changing the API. This should hopefully be complete very soon. In the course of this, I will also update / extend the documentation.
Cheers,
Andre

**Comment by jfass** [comment]
I'd like to follow up on this, Andre. I'm running a build step with 8 samples at the moment (wanting to test 4 vs 4 eventually), --parallel 16, and I haven't seen it using more than a core, been running for about 10 day so far. My command is:

`spladder build --parallel 16 --bams excap1.bam,excap2.bam,excap3.bam,excap4.bam,total1.bam,total2.bam,total3.bam,total4.bam --annotation ../RawData/ucsc_hg19.gtf --outdir total_vs_capture.spladder > total_vs_capture.out 2> total_vs_capture.err &`

It's running in a miniconda virtual environment using Python 3.5.2. Anything I'm missing here? Is there a better way to run large numbers of samples?

**Comment by vjbaskar** [comment]
> Dear vjbaskar,
> I am currently porting SplAdder to Python3, also changing the API. This should hopefully be complete very soon. In the course of this, I will also update / extend the documentation.
> Cheers,
> Andre

Thanks Andre. I can now see that it is in Python 3. Do you have any tips on running spladder on multiple bam files? Is there a way to get PSI for one bam file at a time and then later concatenating them?

Thanks!
Vijay

**Comment by akahles** [comment]
Based on the conversations with @jfass and the previous projects in the lab we have run, I have extended the documentation to include some guidelines for larger cohorts. Here the direct link:
https://spladder.readthedocs.io/en/latest/spladder_cohort.html

I will close this for now. Please open a new issue if you have a specific question regarding the documentation or running on larger cohorts.
