### ISSUE TITLE
Error during visualization

### ISSUE THREAD

**Issue by CindyBay** [ratschlab/spladder#74]
Hi, 
first thank you for developing this nice tool. 
I tried to visualize the example but unfortunately i got this error:

Traceback (most recent call last):
  File "spladder_viz.py", line 360, in <module>
    spladder_viz()
  File "spladder_viz.py", line 117, in spladder_viz
    gene_names = get_gene_names(CFG)
  File "/home/spladder-master/python/modules/identity.py", line 35, in get_gene_names
    gene_names = cPickle.load(open(gene_name_file, 'r'))
IOError: [Errno 2] No such file or directory: 'examples/result_tiny/spladder/genes_graph_conf3.merge_graphs.names.pickle'

It seems to me like the script spladder_viz.py was not able to generate the file:  examples/result_tiny/spladder/genes_graph_conf3.merge_graphs.names.pickle
Did i miss a step before running example_viz.sh?

I would be very happy for help.
Kind regards, 
Cindy

**Comment by akahles** [comment]
This should have been handled in the latest release available. Please re-open, if the error still persists.
