### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

### ISSUE THREAD

**Issue by upendrak** [ratschlab/spladder#80]
* spladder version: 2.0.1
* Python version: 3.6.7
* Operating System: Ubuntu 18.04

### Description

@akahles 

After running the spladder build step with the Spladder 2.0.1, I am getting this error. I am not sure if I am running the visualization step correctly as there is no wiki page for this subcommand of Spladder. Let me know if you need more details.

### What I Did

```
spladder viz -o spladder_build -b TCS10-1-A7_trimmed.sorted.bam,TCS10-2-A8_trimmed.sorted.bam,THS10-1-A10_trimmed.sorted.bam,THS10-2-A11_trimmed.sorted.bam -L WT1,WT2,MT1,MT2 -g "FvH4_c10g00030"
Traceback (most recent call last):
  File "/usr/local/bin/spladder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder.py", line 190, in main
    options.func(options)
  File "/usr/local/lib/python3.6/dist-packages/spladder/spladder_viz.py", line 43, in spladder_viz
    options = settings.parse_args(options, identity='viz')
  File "/usr/local/lib/python3.6/dist-packages/spladder/settings.py", line 203, in parse_args
    if not os.path.isfile(fname):
  File "/usr/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
```

**Comment by sagarutturkar** [comment]
I am having the same issue. Please let me know if you have any workaround for this.

**Comment by upendrak** [comment]
@sagarutturkar I am waiting for @akahles to respond to my question.

**Comment by akahles** [comment]
Dear @upendrak an @sagarutturkar ,

sorry for the late reply. I have just pushed a fix for this bug to the development branch and will add it to the next release.

@upendrak: Just as a side note (unrelated to the fixed bug). The current way how the `-L` parameter is interpreted is as a group name. The call you posted above will throw an error. If you have four files (e.g., 2 wild type WT1, WT2 and 2 mutant MT1 and MT2), then you could group them via `-b WT1.bam,WT2.bam:MT1.bam,MT2.bam` and name the groups as `-L wild-type,mutant`. In the current implementation, the number of labels given, needs to match the number of groups. As your list following `-b` does not contain a group-separator (`:`), only one group label is allowed.

Cheers,

Andre

**Comment by akahles** [comment]
Just released version 2.2.0. Please re-open, if error still persists.

**Comment by sagarutturkar** [comment]
Thank you. I upgraded to version 2.2.0.  
The `test` command generated the output directory **testing_shCBX7_vs_shscrambled**

```
spladder test \
--outdir ./output \
-a T1.bam,T2.bam,T3.bam \
-b C1.bam,C2.bam,C3.bam \
--labelA shCBX7 \
--labelB shscrambled \
--parallel 20
```
Next, the `viz` command generated **FileNotFoundError**
```
spladder viz \
--outdir ./output \
--bams  T1.bam,T2.bam,T3.bam:C1.bam,C2.bam,C3.bam \
--test-result 10 \
--labels shCBX71,shscrambled \
--verbose

Traceback (most recent call last):
  File "/group/bioinfo/apps/apps/spladder-2.2.0/bin/spladder", line 11, in <module>
    load_entry_point('spladder==2.2.0', 'console_scripts', 'spladder')()
  File "/group/bioinfo/apps/apps/spladder-2.2.0/lib/python/spladder-2.2.0-py3.6.egg/spladder/spladder.py", line 192, in main
    options.func(options)
  File "/group/bioinfo/apps/apps/spladder-2.2.0/lib/python/spladder-2.2.0-py3.6.egg/spladder/spladder_viz.py", line 110, in spladder_viz
    SETUP = pickle.load(open(os.path.join(testdir, 'test_setup_C%i_%s.pickle' % (options.confidence, event_type)), 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/output/testing_condA_vs_condB/test_setup_C3_exon_skip.pickle'
```
I also tried to rename the output directory as **testing_condA_vs_condB** and then run below command without specific labels/BAMs to get **IndexError**
```
spladder viz --outdir /scratch/halstead/s/sutturka/spladder_test/spladder/output \
--test-result 10 \
--verbose


Traceback (most recent call last):
  File "/group/bioinfo/apps/apps/spladder-2.2.0/bin/spladder", line 11, in <module>
    load_entry_point('spladder==2.2.0', 'console_scripts', 'spladder')()
  File "/group/bioinfo/apps/apps/spladder-2.2.0/lib/python/spladder-2.2.0-py3.6.egg/spladder/spladder.py", line 192, in main
    options.func(options)
  File "/group/bioinfo/apps/apps/spladder-2.2.0/lib/python/spladder-2.2.0-py3.6.egg/spladder/spladder_viz.py", line 113, in spladder_viz
    idx1 = sp.where(sp.in1d(SETUP[0], SETUP[6]['conditionA']))[0]
IndexError: tuple index out of range

```
Can you please help with this.

**Comment by akahles** [comment]
I have re-written the visualisation part of SplAdder, including a new documentation (https://spladder.readthedocs.io/en/latest/spladder_modes.html#the-viz-mode). Please re-open the issue, in case your problem still occurs with the updated code.
