### ISSUE TITLE
Restart of killed process

### ISSUE THREAD

**Issue by kalmSveta** [ratschlab/spladder#82]
* spladder version: latest
* Python version: 3.6
* Operating System: linux

1) I have run multiple bam files with spladder build. However, there were some technical issues on my server, so the process was killed. Before the crash, a merge_graphs.pickle was created. Now the server is back on and I want to restart the spladder. However, I don't want to repeat the same operations, as it took a lot of time. So, can I use the ready graph?

2) The other question is about the different experiment. It was run in a separate run and only pickle files for some of the bam files (25/100) were created. No merged_graph was created yet. So can I restart the spladder from this moment?

**Comment by akahles** [comment]
Dear kalmSveta,

1) If the merge_graphs.pickle was completely written before your server went down, you can continue from this point. SplAdder should detect any existing file and not re-compute it.
2) Similar to the previous question, SplAdder should only recompute the individual pickle files that are not yet present. 

Best,
Andre

**Comment by kalmSveta** [comment]
That's great news! Thank you very much!

**Comment by akahles** [comment]
Closing, as questions seems to have been answered.
