### ISSUE TITLE
Confidence in spladder results

### ISSUE THREAD

**Issue by CriticalPeriod** [ratschlab/spladder#84]
* spladder version:2.21
* Python version: 3.67
* Operating System: linux mint 19 cinnamon

Hi Andre, 
First of all, thank you for your great tool, I was reading your manuscript and it's very well documented, even though the online documentation on how to actually use it was more sparse.
You will surely understand rapidply that i'm new in bioinformatics, and I'm kind of self-formed, so I may struggle with very simple things. 
I'm using spladder to perform differential expression of alternative splicing events for the next paper of the lab; 
I managed to run it in build mode (with the ignore mismatches options, how much does it affect the results ?) 
I found how to lunch "test" but there is a lack of documentation. 
I got some errors while running it, such as impossible to divide by 0, warningRunTime due to expect less or greater etc. 
Indeed I got some files .tsv in the results folder 
So now, I have some problems 

0/What is the difference between events labeled with unique and those not ? 

1/I have files with p values that seem correct- they point out dozens of genes under the significance. but all padj are equal to the same value. 

2/ Genes are still labeled with ENSMUG00000... while I provided annotation files in the build phase. Is there a way quicker than copy/paste in google each to know the name of the gene ?
like a tool to provide additional informaton directly on the browser. 

event_id	gene	p_val	p_val_adj	mean_event_count_A	mean_event_count_B	log2FC_event_count	mean_gene_exp_A	mean_gene_exp_B	log2FC_gene_exp
exon_skip_8349	gene:ENSMUSG00000020220	0.000994825497224	0.999881196020385	3.47362099737114	14.218774329537	-2.03328485175635	6424.03804637412	6830.64317463032	-0.088540992100526
exon_skip_3842	gene:ENSMUSG00000022564	0.003158499187098	0.999881196020385	45.1371136951515	25.1902248891313	0.841450165973382	2558.75356436522	2580.52613731664	-0.012224036352144
exon_skip_2480	gene:ENSMUSG00000020598	0.006823912411492	0.999881196020385	115.028779455316	79.7690454822491	0.528093939463497	16944.9729231591	16499.1781032411	0.038463172237094
exon_skip_12726	gene:ENSMUSG00000031167	0.009234896247496	0.999881196020385	0	2.65354545692488	-inf	1505.42191389939	1351.49342999188	0.155613379016396
exon_skip_7244	gene:ENSMUSG00000005687	0.009542584299552	0.999881196020385	34.7162507030381	19.566118293644	0.827253578294288	1234.39444485886	1265.06558534337	-0.035408706642375
exon_skip_8018	gene:ENSMUSG00000028760	0.010092442561373	0.999881196020385	6.42819982863409	2.1386036709481	1.58774563269854	5239.47176460715	6335.88933266764	-0.27412576763377
exon_skip_4452	gene:ENSMUSG00000022867	0.011913741470268	0.999881196020385	8.41787832014932	2.25769324824637	1.89860717466448	1557.18360151036	1568.31897599684	-0.010279957942062
exon_skip_5006	gene:ENSMUSG00000003279	0.012844521360348	0.999881196020385	42.096044690971	63.411667481764	-0.591063629401415	12659.7069140987	12816.7388367999	-0.017785215997678
exon_skip_9808	gene:ENSMUSG00000030002	0.013000604840713	0.999881196020385	15.3385079539939	6.45606406310159	1.24843135262981	1268.66366059631	1288.87916417162	-0.022807371105124
exon_skip_1375	gene:ENSMUSG00000035798	0.015642211627504	0.999881196020385	22.3190153998583	34.1019083048185	-0.611579088829028	3744.4441323272	3438.51589579113	0.122965549605365
exon_skip_1162	gene:ENSMUSG00000044071	0.020440849172273	0.999881196020385	7.43967179995276	2.45561935258562	1.59915203366479	2648.6916483594	2832.17434407821	-0.096630178280121
exon_skip_2517	gene:ENSMUSG00000055884	0.020501869682488	0.999881196020385	2.48876138695015	0	inf	1034.09749978133	898.264166670892	0.203160527927547
exon_skip_12111	gene:ENSMUSG00000032517	0.021955490781681	0.999881196020385	212.755984826021	224.536506427923	-0.077750310143411	7056.82789750249	9665.6357205661	-0.453844797501862

3/viz does not work 
 spladder viz  -b p30_all/p30_+-_1.bam,p30_all/p30_+-_2.bam:p30_all/p30_++_1.bam,p30_all/p30_++_2.bam  -o spladder_results/ -L het,homo 
Traceback (most recent call last):
  File "/home/david/anaconda3/envs/spladder/bin/spladder", line 10, in <module>
    sys.exit(main())
  File "/home/david/anaconda3/envs/spladder/lib/python3.6/site-packages/spladder/spladder.py", line 191, in main
    options.func(options)
  File "/home/david/anaconda3/envs/spladder/lib/python3.6/site-packages/spladder/spladder_viz.py", line 43, in spladder_viz
    options = settings.parse_args(options, identity='viz')
  File "/home/david/anaconda3/envs/spladder/lib/python3.6/site-packages/spladder/settings.py", line 203, in parse_args
    if not os.path.isfile(fname):
  File "/home/david/anaconda3/envs/spladder/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list

There is 2 replicates & 2 conditions ( 4 samples in total) each was preprocesses with STAR (without the -NM flag) reads are 51bp, single-end. I never indicate the lenght in any command nor test nor build. 
I'm running under Linux Mint CInnamon, python 3.6 in anaconda3 virtual environnement, with all required packages. 

Thank you if you can help me. This results look promising but i'm currently lacking confidence in them. 
David Benacom
College de France, Paris

**Comment by akahles** [comment]
Most of the issue brought up here were addressed in the meantime.

0/ -> description of testing outputs has been added to the docs
1/ -> This can happen for small testing cohorts
2/ -> The synonymous name provided in the input annotation should now be carried through to the output
3/ -> visualization has been rewritten to allow for better way of plotting, documentation has been added.

Thanks again for the inputs and critical feedback. 

I am closing this for now. Please re-open if anything should still pop up with the latest release.
