### ISSUE TITLE
Visualization error

### ISSUE THREAD

**Issue by aparnashree** [ratschlab/spladder#85]
* spladder version:2.2.1
* Python version:3.5.2
* Operating System:Ubuntu 16.04.2

Hi Andre,
I and trying to visualize my spladder results. I have updated to the latest version of spladder and used the following commands:
spladder viz -o ./merged -b all/A_1/A_1_sorted.bam,all/A_2/A_2_sorted.bam,all/A_3/A_3_sorted.bam:all/B1/B1_sorted.bam,all/B2/B2_sorted.bam,all/B3/B3_sorted.bam:all/C_1/C_1_sorted.bam,all/C_2/C_2_sorted.bam,all/C_3/C_3_sorted.bam -L A,B,C -v -t exon_skip,intron_retention,alt_3prime,alt_5prime,mult_exon_skip -f png

Its throwing this error:
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/spladder", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/spladder/spladder.py", line 192, in main
    options.func(options)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/spladder/spladder_viz.py", line 202, in spladder_viz
    _plot_event(options, event_info, fig, axes, gs, xlim)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/spladder/spladder_viz.py", line 282, in _plot_event
    event_list = [_ for event in load_events(options, event_info) for _ in [event.exons1, event.exons2]]
  File "/home/ubuntu/.local/lib/python3.5/site-packages/spladder/helpers_viz.py", line 86, in load_events
    events = pickle.load(open(os.path.join(options.outdir, 'merge_graphs_%s_C%s.pickle' % (event_type, options.confidence)),'rb'), encoding='latin1')
ImportError: No module named 'modules'

Could you please help me with this?
Thank you.

**Comment by akahles** [comment]
Dear @aparnashree ,

Thank you for reporting this issue. Are you visualizing results generated with SplAdder 2.x.x or from an earlier version still running under python 2.7?

Thanks,

Andre

**Comment by aparnashree** [comment]
Dear @akahles ,

Thank you for your reply. I ran the spladder test in the newer version but the first part was done in the older version.

Thanks,
Aparna

**Comment by akahles** [comment]
Thank you for the fast reply. Some of the data structures within SplAdder have changed, which makes direct application to alder results a bit tricky. I will try to add fix for this and comment here, once this is done.

Best,
Andre

**Comment by aparnashree** [comment]
Dear @akahles,
Just wanted to know if there was any update on this issue.

Thanks,
Aparna

**Comment by akahles** [comment]
Dear @aparnashree,

I have re-written the visualisation part of SplAdder for the latest release. There is also more documentation available now. Also plotting on data generated with earlier versions should work (except for the `--test` option, which needs additional data that has not been generated in the older versions). I will close this for now. Please re-open the issue if the same problem still arises with the new code.

Best,
Andre
