### ISSUE TITLE
Unable to execute after fresh install

### ISSUE THREAD

**Issue by lemetrec** [ratschlab/spladder#86]
* spladder version: current (uknown)
* Python version: 3
* Operating System: ubuntu (on AWS)

### Description

Hi!
Right after installation that went smoothly, I tried the command with just the bin as mentioned in the manual, but it is throwing an error. Trying spladder with an "--h" or "--help" also fails. It is as if the exe was waiting for arguments no matter what..

### What I Did

```
$ spladder

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/spladder", line 7, in <module>
    from spladder.spladder import main
  File "/home/ubuntu/.local/lib/python2.7/site-packages/spladder/spladder.py", line 3, in <module>
    from .spladder_build import spladder
  File "/home/ubuntu/.local/lib/python2.7/site-packages/spladder/spladder_build.py", line 78
    print('ERROR: Unknown annotation format. File needs to end in gtf or gff/gff3\nCurrent file: %s' % (options.annotation), file=sys.stderr)
                                                                                                                                 ^
SyntaxError: invalid syntax
```
Any idea how I can remedy this?

Many thanks!

**Comment by akahles** [comment]
Dear @lemetrec,

Thank you very much for trying out SplAdder. From your error message I take that you did invoke SplAdder using Python 2.7. Beginning with version 2.0.0, SplAdder requires Python 3. 
I have now added an error message for this case, to make this more apparent.

Thanks,

Andre

**Comment by lemetrec** [comment]
Thank you Andre. Indeed I had an issue with the Python version calling.

On a side note, I had issues getting it to work due to conflicting package versions, especially in scipy:

```
    from scipy.misc import factorial
ImportError: cannot import name 'factorial'
```

 I had to downgrade from 1.3 to 1.2 (after finding the following: https://stackoverflow.com/questions/56283294/importerror-cannot-import-name-factorial) with:

`sudo python3.6 -m pip install scipy==1.2 --upgrade`

Thank you!

**Comment by akahles** [comment]
Thanks for reporting. This is in fact a problem in statsmodels. I have restricted the requirements to scipy<1.3 for now until this is fixed.

Cheers,
Andre
