### ISSUE TITLE
ValueError: Zero sized dimension

### ISSUE THREAD

**Issue by lkmklsmn** [ratschlab/spladder#9]
Hi andre,
I am trying to run the example_run.sh script. I made sure that I have the correct versions of h5py, scipy and pysam installed. But when I run:

python spladder.py -b examples/NMD_WT1.tiny.bam,examples/NMD_WT2.tiny.bam,examples/NMD_DBL1.tiny.bam,examples/NMD_DBL2.tiny.bam -o test -a examples/TAIR10_GFF3_genes.tiny.gff -v y -M merge_graphs -t exon_skip,intron_retention,alt_3prime,alt_5prime,mutex_exons,mult_exon_skip -c 3 -p n #-e n

I get the following error:

Augmenting splice graphs.
=========================
Generating splice graph ...

Total genes:                                                    1
Total genes with alternative isoforms:                          1
Total genes alternatively spliced:                              1
Total constitutively spliced:                                   0
...done.

Loading introns from file ...
...done.

Testing for infeasible genes ...
found 0 unfeasible genes
...done.

Inserting cassette exons ...

... inserted 0 casette exons ....
... done.

Inserting intron retentions ...

... inserted 0 new intron retentions ...
...done.

Inserting new intron edges ...
... chr Chr1 - iteration 1/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 2/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 3/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 4/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 5/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... done.

Re-labeleling new alternative genes ...
... done.

Inserted:
        alt_53_prime:   0
        intron_retention:       0
        new_terminal_exon:      0
        exon_skip:      2
        gene_merge:     0
        cassette_exon:  0
        intron_in_exon: 0
Saving genes to test/spladder/genes_graph_conf3.NMD_WT1.tiny.pickle
No pruning requested!
Generating all isoforms not requested
Augmenting splice graphs.
=========================
Generating splice graph ...

Total genes:                                                    1
Total genes with alternative isoforms:                          1
Total genes alternatively spliced:                              1
Total constitutively spliced:                                   0
...done.

Loading introns from file ...
...done.

Testing for infeasible genes ...
found 0 unfeasible genes
...done.

Inserting cassette exons ...

... inserted 0 casette exons ....
... done.

Inserting intron retentions ...

... inserted 0 new intron retentions ...
...done.

Inserting new intron edges ...
... chr Chr1 - iteration 1/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 2/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 3/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 4/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 5/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... done.

Re-labeleling new alternative genes ...
... done.

Inserted:
        alt_53_prime:   0
        intron_retention:       0
        new_terminal_exon:      0
        exon_skip:      2
        gene_merge:     0
        cassette_exon:  0
        intron_in_exon: 0
Saving genes to test/spladder/genes_graph_conf3.NMD_WT2.tiny.pickle
No pruning requested!
Generating all isoforms not requested
Augmenting splice graphs.
=========================
Generating splice graph ...

Total genes:                                                    1
Total genes with alternative isoforms:                          1
Total genes alternatively spliced:                              1
Total constitutively spliced:                                   0
...done.

Loading introns from file ...
...done.

Testing for infeasible genes ...
found 0 unfeasible genes
...done.

Inserting cassette exons ...

... inserted 0 casette exons ....
... done.

Inserting intron retentions ...

... inserted 0 new intron retentions ...
...done.

Inserting new intron edges ...
... chr Chr1 - iteration 1/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 2/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 3/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 4/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 5/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... done.

Re-labeleling new alternative genes ...
... done.

Inserted:
        alt_53_prime:   0
        intron_retention:       0
        new_terminal_exon:      1
        exon_skip:      2
        gene_merge:     0
        cassette_exon:  0
        intron_in_exon: 0
Saving genes to test/spladder/genes_graph_conf3.NMD_DBL1.tiny.pickle
No pruning requested!
Generating all isoforms not requested
Augmenting splice graphs.
=========================
Generating splice graph ...

Total genes:                                                    1
Total genes with alternative isoforms:                          1
Total genes alternatively spliced:                              1
Total constitutively spliced:                                   0
...done.

Loading introns from file ...
...done.

Testing for infeasible genes ...
found 0 unfeasible genes
...done.

Inserting cassette exons ...
/home/simonlm/programs/spladder/python/modules/editgraph.py:843: RuntimeWarning: divide by zero encountered in double_scalars
  (sp.median(exon_cov[:min_len_pre]) / sp.median(pre_segment_cov[-min_len_pre:])) - 1 >= CFG['cassette_exon']['min_cassette_rel_diff']:

... inserted 1 casette exons ....
... done.

Inserting intron retentions ...

... inserted 0 new intron retentions ...
...done.

Inserting new intron edges ...
... chr Chr1 - iteration 1/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 2/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 3/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 4/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... chr Chr1 - iteration 5/5

... removing duplicate exons ...
0

... removed 0 duplicate exons ...
... done.

Re-labeleling new alternative genes ...
... done.

Inserted:
        alt_53_prime:   0
        intron_retention:       0
        new_terminal_exon:      1
        exon_skip:      3
        gene_merge:     0
        cassette_exon:  1
        intron_in_exon: 0
Saving genes to test/spladder/genes_graph_conf3.NMD_DBL2.tiny.pickle
No pruning requested!
Generating all isoforms not requested
Loading test/spladder/genes_graph_conf3.NMD_WT1.tiny.pickle ...
... done (1 / 4)
Loading test/spladder/genes_graph_conf3.NMD_WT2.tiny.pickle ...
... done (2 / 4)
Processing ...
. 0/1
... done

Loading test/spladder/genes_graph_conf3.NMD_DBL1.tiny.pickle ...
... done (3 / 4)
Processing ...
. 0/1
... done

Loading test/spladder/genes_graph_conf3.NMD_DBL2.tiny.pickle ...
... done (4 / 4)
Processing ...
. 0/1
... done

Store genes at: test/spladder/genes_graph_conf3.merge_graphs.pickle

1/4
.
2/4
.
3/4
.
4/4
.
confidence 3 / sample 0 / replicate 0
Loading gene structure from test/spladder/genes_graph_conf3.merge_graphs.pickle ...
... done.
.
Number of intron retentions:                                    0
.
Number of single exon skips:                                    2
.
Number of alternative 5 prime sites:                            2
Number of alternative 3 prime sites:                            2
. Number of multiple exon skips:                                        0
.

Number of XOR exons:                                            0

saving intron retentions to test/merge_graphs_intron_retention_C3.pickle

Make exon_skip events unique by strain
events dropped: 0

Make exon_skip events unique by event
events dropped: 0
saving exon skips to test/merge_graphs_exon_skip_C3.pickle
saving multiple exon skips to test/merge_graphs_mult_exon_skip_C3.pickle

Make alt_5prime events unique by strain
events dropped: 0

Make alt_5prime events unique by event
events dropped: 0
Corrected 1 events
Removed 0 events
saving alt 5 prime events to test/merge_graphs_alt_5prime_C3.pickle

Make alt_3prime events unique by strain
events dropped: 0

Make alt_3prime events unique by event
events dropped: 0
Corrected 1 events
Removed 0 events
saving alt 3 prime events to test/merge_graphs_alt_3prime_C3.pickle
saving mutually exclusive exons to test/merge_graphs_mutex_exons_C3.pickle
confidence 3 / replicate 0
0/4
1/4
2/4
3/4
0/4
1/4
2/4
3/4

Reporting complete exon_skip events:

Reporting confirmed exon_skip events:
writing exon_skip events in gff3 format to test/merge_graphs_exon_skip_C3.confirmed.gff3
writing exon_skip events in flat txt format to test/merge_graphs_exon_skip_C3.confirmed.txt
confidence 3 / replicate 0

No intron_retention event could be found. - Nothing to report
confidence 3 / replicate 0
0/4
1/4
2/4
3/4
0/4
1/4
2/4
3/4
Traceback (most recent call last):
  File "spladder.py", line 215, in <module>
    spladder()
  File "spladder.py", line 211, in spladder
    analyze_events(CFG, CFG['event_types'][idx])
  File "/home/simonlm/programs/spladder/python/modules/alt_splice/analyze.py", line 193, in analyze_events
    OUT.create_dataset(name='conf_idx', data=confirmed_idx)
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/group.py", line 99, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 114, in make_new_dset
    sid = h5s.create_simple(shape, maxshape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2400)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2357)
  File "h5py/h5s.pyx", line 99, in h5py.h5s.create_simple (/tmp/pip_build_root/h5py/h5py/h5s.c:1346)
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)

It seems to run fine for a large part but then it gives me this "Zero sized dimension" error. 
Can you help?

**Comment by akahles** [comment]
I am terribly sorry for my late reply. It somehow fell through while I was traveling. Could you please let me know with which h5py version you are working? You can use
```
import h5py
h5py.__version__
```

**Comment by lkmklsmn** [comment]
Thanks for responding anyways. In the meantime I have gotten the example
script to run. I cant remember exactly what the solution was but I think
fuzzing around with the h5py version was what did it in the end.
However, I am still having trouble using spladder successfully.
1. Can you point me to a resource where I can download annotation files
(like the TAIR10 one in the example but for hg19 for example)?
2. I was able to run the spladder command on a small set of my bamfiles
without any error. How do I go about obtaining the results? I have a number
of ".pickle" files. I am not familiar with this format but I was wondering
if all results are in this format. How would I go about checking the
results? Using the pickle module in python or there any other way?

Thanks



2015-07-08 18:40 GMT-05:00 Andre Kahles <notifications@github.com>:

**Comment by akahles** [comment]
1.) SplAdder can take annotation files in standardized GTF or GFF formation as input. Depending on the organism you are working on, they can be obtained from various sources. If you are working with human, one such repo would be the GENCODE site: 
http://www.gencodegenes.org/releases/current.html
2.) SplAdder generates output in various formats. I would not recommend to work with the pickle files as their content is more for internal use. All detected events are output as standard GTF file. In addition to that SplAdder also outputs all events plus their count values as a HDF5 file. This is a hierarchically structured file format that can be accessed in a standardized way from many different languages (python, C++, Matlab, ...). 

I am currently writing a small tutorial on SplAdder that will hopefully help the understanding of input and output files as well as certain use cases. It should be finished really soon and I will post here when it is available.

**Comment by lkmklsmn** [comment]
Thanks for the quick answer. In my case I cannot find any gtf result file.
I did not get any error messages during the run but could this be that no
alternative splicing event was detected?

I think a tutorial would be a great idea. The paper was great and now I
cant wait to use it on my own data!


2015-07-10 15:35 GMT-05:00 Andre Kahles <notifications@github.com>:

**Comment by satoshitakahashi** [comment]
Hi andre,
I got the same error when I run the example_run.sh.

h5py.__version__
'2.5.0'
scipy.__version__
'0.15.1'
pysam.__version__
'0.8.2.1'


Traceback (most recent call last):
  File "spladder.py", line 215, in <module>
    spladder()
  File "spladder.py", line 211, in spladder
    analyze_events(CFG, CFG['event_types'][idx])
  File "/home/tool/spladder-master/python/modules/alt_splice/analyze.py", line 193, in analyze_events
    OUT.create_dataset(name='conf_idx', data=confirmed_idx)
  File "/usr/local/Python/lib/python2.7/site-packages/h5py/_hl/group.py", line 103, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/usr/local/Python/lib/python2.7/site-packages/h5py/_hl/dataset.py", line 120, in make_new_dset
    sid = h5s.create_simple(shape, maxshape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-OAP2Nq/h5py/h5py/_objects.c:2467)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-OAP2Nq/h5py/h5py/_objects.c:2424)
  File "h5py/h5s.pyx", line 99, in h5py.h5s.create_simple (/tmp/pip-build-OAP2Nq/h5py/h5py/h5s.c:1416)
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)

**Comment by akahles** [comment]
Thanks for reporting. I have run SplAdder with the same package configuration and could not reproduce the error. It might originate from some underlying system hdf5. The problem seems to be related to the creation of an empty dataset. I will change to code to hopefully prevent that problem.

**Comment by akahles** [comment]
It might indeed be the hdf5 version. Could you please tell me your hdf5 version? You can get this via:
```
h5py.version.hdf5_version
```

**Comment by akahles** [comment]
I have prevented SplAdder from writing the field when it is empty. Could you please try if that solves your problem?

**Comment by satoshitakahashi** [comment]
Thank you for fixing the issue quickly!
I have finished 'SplAdder Tutorial' successfully. 
I report hdf5 version.

h5py.version.hdf5_version
'1.8.5'

**Comment by akahles** [comment]
Thanks for reporting back the version. There seems to be an issue with versions <= 1.8.7:
https://github.com/h5py/h5py/issues/559

I will close this for now. Please re-open if similar problems pop up again.
