### ISSUE TITLE
Options for large cohorts

### ISSUE THREAD

**Issue by jfass** [ratschlab/spladder#98]
We've conversed quite a bit, Andre (thanks for your responsiveness!) about running with large cohorts. I've read the new instructions on the readthedocs site, but I still have questions / problems.

When I try to use --sparse-bams, I get these errors:
```
KeyError: "Unable to open object (object 'chr3_reads_dat' doesn't exist)"
```

When I launch multiple jobs for the same BAM, running separately on single-chromosome GTF files, spladder chokes on everything but the first run, because either the single-chromosome GTF file has a ".pickle" file started, but not yet completed ... or because the BAM has a ".hdf5" file started, but not completed.

Would it be possible to get some "indexing" commands, to separately generate .pickle, .hdf5, or the spare bam files *before* launching parallel jobs? I can get around all of these by running a single, small chromosome first, or a dummy BAM file, but it would be nice not to have to. Or maybe I'm missing something ...

The documentation on --sparse-bams is pretty ... sparse. It's not clear whether the option takes an argument, what file names it generates, or if one could save disk space by removing the BAM files after the sparse bams are generated ...?

Thanks,
~Joe

**Comment by akahles** [comment]
Hi Joe,

I will extend the docs in this direction. Essentially, for each input bam file a summary hdf5 file is generated. That the contig can not be found is indeed curious. Could you provide some more details on the command line that produced that error? How were the gtf files / bam files split into chromosomes?

Regarding the parallelization - it creates a race condition when several processes try creating the same output file. So essentially, one needs to pre-process the annotation file(s) first for each chunk. I can add this bit to the documentation. 
An alternative would be to use locks from the file system to figure out whether the file is already currently written by another process. I will add this to my todo list.

Cheers,

Andre
